;
; ini file for language information
;

[COMMON]
defaultLanguage = russian
;defaultLanguage	= english
;defaultLanguage	= german
;defaultLanguage	= spanish
;defaultLanguage	= french
;defaultLanguage	= italian
;defaultLanguage    = portuguese
;defaultLanguage    = polish
;defaultLanguage    = chinese
strings = common.ini
GlobalFile = globals.txt

[DIRECTORY]
Russian = russian
English = english
German = german
Spanish = spanish
French = french
Italian = italian
Portuguese = portuguese
Polish = polish
Chinese = chinese

[FONTS]
Russian = fonts_rus.ini
English = fonts_rus.ini
Spanish = fonts_rus.ini
German = fonts_rus.ini
French = fonts_rus.ini
Italian = fonts_rus.ini
Portuguese = fonts_rus.ini
Polish = fonts_rus.ini
Chinese = fonts_chs.ini

