; Ugeen. Интерфейс мультиобъектов 26.08.10
; KZ > ref 15.12.24

[MAIN]
item = FRAME,MAIN_FRAME
item = WINDOW,MAIN_WINDOW
item = 10,PICTURE,MAIN_BACK
item = 10,SLIDEPICTURE,DUST
item = 10,SLIDEPICTURE,BUBBLES
item = 200,TABLE,TABLE_LIST
item = 202,TEXTBUTTON2,GETALL_BUTTON
item = 201,SCROLLER,SCROLL_LIST
item = 501,FORMATEDTEXT,QTY_SELECTED
item = 501,FORMATEDTEXT,RESULT_DONE
item = 501,FORMATEDTEXT,RESULT_CRAFT
item = 501,FORMATEDTEXT,QTY_CREATE
item = 501,FORMATEDTEXT,RESULT_QTY
item = 201,SCROLLIMAGE,ITEMS_SCROLL
item = 201,PICTURE,BUG_L_PICTURE
item = 201,PICTURE,BUG_R_PICTURE
item = 209,BUTTON,LEFTSCROLLBUTTON
item = 209,BUTTON,RIGHTSCROLLBUTTON
item = 209,BUTTON,INCREASE_BUTTON
item = 209,BUTTON,DECREASE_BUTTON
item = 209,BUTTON,INCREASE_ALL_BUTTON
item = 209,BUTTON,DECREASE_ALL_BUTTON

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	TOP_MENU
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = PICTURE,TOP_LINE
item = PICTURE,TAB_MARK
item = PICTURE,TAB_GLOW
item = BUTTON,I_CHARACTER_2
item = BUTTON,I_SHIP_2
item = BUTTON,I_QUESTBOOK_2
item = BUTTON,I_ALCHEMY_2
item = BUTTON,I_ITEMS_2
item = BUTTON,I_NATIONS_2
item = STRINGCOLLECTION,STR_BUTTONS
item = STRINGCOLLECTION,STR_TITLE
item = 400,IMAGECOLLECTION,KEY_BTNS
item = 400,STRINGCOLLECTION,KEY_STRS
item = IMAGECOLLECTION,ADD_INFO
item = FORMATEDTEXT,WEIGHT
item = FORMATEDTEXT,MONEY
item = FORMATEDTEXT,CURRENT_DATE_CAPTION
item = ALERT,A_QUESTBOOK
item = ALERT,A_RECIPE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	TUTORIAL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 30001,RECTANGLE,TUTORIAL_FADER
item = 30002,FRAME,TUTORIAL_MAIN_FRAME
item = 30002,TOOLTIP_TITLERECT,TUTORIAL_TITLERECT
item = 30002,FORMATEDTEXT,TUTORIAL_TITLE
item = 30002,PICTURE,TUTORIAL_INFO_PICTURE
item = 30004,VIDEORECTANGLE,TUTORIAL_INFO_VIDEO
item = 30005,PICTURE,TUTORIAL_VFRAME
item = 30005,FRAME,TUTORIAL_VFRAME_BORDER
item = 30005,FORMATEDTEXT,TUTORIAL_ZOOM
item = 30005,PICTURE,TUTORIAL_ZOOMPLUS
item = 30002,FORMATEDTEXT,TUTORIAL_INFO_TEXT
item = 30002,SCROLLER,TUTORIAL_SCROLL_TEXT
item = 30002,FORMATEDTEXT,TUTORIAL_CONTROLS_TEXT
item = 30002,FORMATEDTEXT,TUTORIAL_CONTROLS_IMG
item = 30002,TEXTBUTTON,TUTORIAL_B_OK
item = 30002,TEXTBUTTON,TUTORIAL_B_OK2
item = 30002,CHECKBUTTON,TUTORIAL_CHECKBOX
item = 30002,WINDOW,TUTORIAL_MAIN_WINDOW
item = 30006,VIDEORECTANGLE,TUTORIAL_INFO_VIDEOZ
item = 30006,FRAME,TUTORIAL_FRAME_ZOOM
item = 30006,PICTURE,TUTORIAL_VFRAMEZ
item = 30002,WINDOW,TUTORIAL_INFO_WINDOW

start = TABLE_LIST

[MAIN_WINDOW]
show = 1
nodelist = FRAME,MAIN_BACK,DUST,BUBBLES,TABLE_LIST,GETALL_BUTTON,SCROLL_LIST,QTY_SELECTED
nodelist = RESULT_DONE,RESULT_CRAFT,QTY_CREATE,RESULT_QTY,ITEMS_SCROLL,BUG_L_PICTURE,BUG_R_PICTURE,LEFTSCROLLBUTTON
nodelist = RIGHTSCROLLBUTTON,INCREASE_BUTTON,DECREASE_BUTTON,INCREASE_ALL_BUTTON,DECREASE_ALL_BUTTON
;; top_menu
nodelist = TOP_LINE,TAB_MARK,TAB_GLOW,I_CHARACTER_2,I_SHIP_2,I_QUESTBOOK_2,I_ALCHEMY_2,I_ITEMS_2,I_NATIONS_2
nodelist = STR_BUTTONS,STR_TITLE,KEY_BTNS,KEY_STRS,ADD_INFO,WEIGHT,MONEY,CURRENT_DATE_CAPTION,A_QUESTBOOK,A_RECIPE


[TOP_LINE]
position = -133,44,933,45
groupName = le_icons
picName = border_hs

[TAB_MARK]
position = 346,43,416,46
groupName = tabs2
picName = TabSelectedMark

[TAB_GLOW]
position = 326,0,437,44
groupName = tabs2
picName = TabSelected
blind = 1
blindUpTime = 2.0
blindDownTime = 2.0
blindMinColor = 50,128,128,128
blindMaxColor = 225,128,128,128

[A_QUESTBOOK]
position = 360,1,374,15

[A_RECIPE]
position = 457,1,471,15

[STR_BUTTONS]
string = buttonCharacter,font:interface_normal,pos:{195,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonShip,font:interface_normal,pos:{282,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonQuestBook,font:interface_normal,pos:{365,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = Sel Items,font:interface_normal,pos:{542,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonNation,font:interface_normal,pos:{624,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}

[STR_TITLE]
string = buttonAlchemy,font:interface_normal,pos:{458,16},fc:{255,255,255,255},bc:{0,128,128,128},scale:1.11,state:{CS}

[KEY_BTNS]
groupName = keyboard_icons
picture = q,col:{255,75,75,75},pos:{91,11,119,38}
picture = e,col:{255,75,75,75},pos:{680,11,708,38}
picture = rmb,col:{255,128,128,128},pos:{537,561,565,588}
picture = esc,col:{255,128,128,128},pos:{680,561,708,588}

[KEY_STRS]
string = help,font:interface_normal,pos:{577,566},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{L}
string = back,font:interface_normal,pos:{724,566},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{L}

[ADD_INFO]
groupName = icons_char
picture = weight,col:{255,128,128,128},pos:{-117,16,-97,36}
picture = money,col:{255,128,128,128},pos:{-31,16,-11,36}

[WEIGHT]
command = click
command = rclick,select:WEIGHT,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = -89,19,-29,36
fontScale = 0.78
lineSpace = 10
alignment = left
bShowGlowCursor = 0

[MONEY]
command = click
command = rclick,select:MONEY,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = -9,19,77,36
fontScale = 0.78
lineSpace = 10
alignment = left
bShowGlowCursor = 0

[CURRENT_DATE_CAPTION]
command = click
position = 707,16,932,38
fontScale = 1.11
lineSpace = 10
alignment = center
string = Current Date and time

[I_CHARACTER_2]
bBreakCommand = 1
command = click
position = 136,0,253,44

[I_SHIP_2]
bBreakCommand = 1
command = click
position = 253,0,341,44

[I_QUESTBOOK_2]
bBreakCommand = 1
command = click
position = 341,0,427,44

[I_ALCHEMY_2]
bBreakCommand = 1
command = click
position = 427,0,499,44

[I_ITEMS_2]
bBreakCommand = 1
command = click
position = 499,0,585,44

[I_NATIONS_2]
bBreakCommand = 1
command = click
position = 585,0,663,44

[MAIN_FRAME]
position = 10,65,790,550
backimage = piclist=RECON_PAPIRUS, piccutuv=(0.0,0.0), color=(255,118,118,128)

[MAIN_BACK]
bAbsoluteRectangle = 0
;position = -134,0,933,600
position = -169,-269,969,869
textureName = interfaces\Recon\bgr_interface.tga

; анимация (крутится)
[DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[BUBBLES]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\bubbles.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[ITEMS_SCROLL]
command = activate
command = click,select:ITEMS_SCROLL
command = rightstep
command = leftstep
command = speedright
command = speedleft
command = deactivate,event:ExitCancel
command = rclick,select:ITEMS_SCROLL,event:ShowHelpHint
LayerQuantity = 2
position = 202,85,608,109
imageSize = 55,55
wDelta = 3
glowoffset = 0,0

[TABLE_LIST]
command = deactivate,event:exitCancel
command = click,select:TABLE_LIST
command = rclick,select:TABLE_LIST,event:ShowHelpHint
command = dblclick,select:TABLE_LIST
command = activate,select:TABLE_LIST
command = upstep
command = downstep
command = rightstep
command = leftstep
command = speedright
command = speedleft
position = 116,146,699,526
scroller = SCROLL_LIST
vlinewidth = 2
hlineheight = 2
headerlineheight = 2
rowquantity = 7
colquantity = 5
fontcellvalignment = center
selectimage = color=(100,160,160,160)
colswidth = 85,80,240,80,80
rowsheight = 25,50,50,50,50,50,50
NormalLineHeight = 50

[SCROLL_LIST]
command = click, select:TABLE_LIST
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 685,146,699,472
baseTexture = interfaces\icons.tga
rollerTexture = interfaces\icons.tga
scrollTexPos = 0,0.75,0.045,1.0
rollTexPos = 0.0625,0.875,0.1075,0.96
begEndTexSize = 0.0835
begEndBaseSize = 18
rollerHeight = 18
ownedcontrol = TABLE_LIST

[LEFTSCROLLBUTTON]
command = activate,select:ITEMS_SCROLL,com:speedleft:ITEMS_SCROLL
command = click,select:ITEMS_SCROLL,com:leftstep:ITEMS_SCROLL,com:activate:LEFTSCROLLBUTTON
position = 347,76,379,119
group = ICONS
picture = left arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[RIGHTSCROLLBUTTON]
command = activate,select:ITEMS_SCROLL,com:speedright:ITEMS_SCROLL
command = click,select:ITEMS_SCROLL,com:rightstep:ITEMS_SCROLL,com:activate:RIGHTSCROLLBUTTON
position = 430,76,462,119
group = ICONS
picture = right arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[INCREASE_BUTTON]
command = activate
command = click
position = 428,483,453,508
group = ARROWS
picture = right
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[DECREASE_BUTTON]
command = activate
command = click
position = 363,483,388,508
group = ARROWS
picture = left
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[INCREASE_ALL_BUTTON]
command = activate
command = click
position = 459,483,484,508
group = ARROWS
picture = right_all
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[DECREASE_ALL_BUTTON]
command = activate
command = click
position = 332,483,357,508
group = ARROWS
picture = left_all
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[GETALL_BUTTON]
position = 355,517,460,542
command = activate
command = click
command = deactivate,event:exitCancel
command = downstep
glowoffset = 0,0
string = CraftIt
;fontScale = 0.85

[QTY_SELECTED]
position = 407,108,427,138
fontScale = 0.7
lineSpace = 10
alignment = right
;backoffset = 1,2,0,-2
;Color = 255,218,165,32

[RESULT_DONE]
position = 157,490,337,520
font = interface_normal
fontScale = 0.9
lineSpace = 10
alignment = left
;Color = 255,255,255,156

[RESULT_CRAFT]
position = 517,490,697,520
font = interface_normal
fontScale = 0.9
lineSpace = 10
alignment = left
;Color = 255,255,255,156

[QTY_CREATE]
position = 382,488,435,518
font = interface_normal
fontScale = 0.9
lineSpace = 10
alignment = center
;Color = 255,255,255,156

[BUG_L_PICTURE]
position = 128,70,192,134
textureName = interfaces\bug_l.tga
blind = 1
blindUpTime = 1.5
blindDownTime = 1.0
blindMinColor = 255,128,128,128
blindMaxColor = 255,168,168,168

[BUG_R_PICTURE]
position = 620,70,684,134
textureName = interfaces\bug.tga
blind = 1
blindUpTime = 1.5
blindDownTime = 1.0
blindMinColor = 255,128,128,128
blindMaxColor = 255,168,168,168


;;;;; TUTORIAL WINDOW
[TUTORIAL_MAIN_WINDOW]
show = 0
nodelist = TUTORIAL_FADER,TUTORIAL_MAIN_FRAME,TUTORIAL_TITLE,TUTORIAL_TITLERECT,TUTORIAL_INFO_PICTURE
nodelist = TUTORIAL_INFO_VIDEO,TUTORIAL_VFRAME,TUTORIAL_VFRAME_BORDER,TUTORIAL_ZOOM,TUTORIAL_ZOOMPLUS,TUTORIAL_INFO_TEXT,TUTORIAL_SCROLL_TEXT,TUTORIAL_B_OK,TUTORIAL_B_OK2
nodelist = TUTORIAL_CONTROLS_TEXT,TUTORIAL_CONTROLS_IMG
nodelist = TUTORIAL_CHECKBOX


[TUTORIAL_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 220,0,0,0
topColor = 220,0,0,0
rightColor = 220,0,0,0
bottomColor = 220,0,0,0
borderColor = 0,0,0,0

[TUTORIAL_MAIN_FRAME]
position = 201,89,600,512
captionheight = 26
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captiondividerheight = 1

[TUTORIAL_TITLERECT]
position = 206,95,595,117

[TUTORIAL_TITLE]
position = 206,92,595,115
fontScale = 1.0
lineSpace = 6
alignment = center
font = INTERFACE_TITLE

[TUTORIAL_INFO_PICTURE]
position = 212,123,589,334
textureName = loading\salary.tga

[TUTORIAL_INFO_VIDEO]
position = 212,123,589,334
textureRect = 0,0,1.0,1.0
videoFile = Pirate.webm
color = 255,128,128,128
loop = 1
silent = 1

[TUTORIAL_VFRAME]
command = click
command = deactivate,event:exitCancel
command = rclick,select:VFRAME,event:ShowInfoWindow
position = 212,123,589,334
textureName = interfaces\empty_back.tga
bShowGlowCursor=0

[TUTORIAL_VFRAME_BORDER]
backimage = piclist=PAPER_FRAME, picname=paper, color=(245,50,50,50)
position = 212,123,589,334

[TUTORIAL_ZOOM]
font = KEYBOARD_SYMBOL
position = 195,310,249,429
fontScale = 0.65

[TUTORIAL_ZOOMPLUS]
groupName = icons
picName = pluss
position = 227,307,236,316

[TUTORIAL_INFO_TEXT]
position = 217,345,584,459
fontScale = 0.85
lineSpace = 16
scrollerName = TUTORIAL_SCROLL_TEXT
command = downstep
command = upstep
command = speeddown
command = speedup
command = deactivate,event:exitCancel
command = activate,select:TUTORIAL_INFO_TEXT
command = click,select:TUTORIAL_INFO_TEXT
moveMouseDoSelect=1
bShowGlowCursor=0

[TUTORIAL_CONTROLS_TEXT]
position = 212,473,301,489
alignment = right
fontScale = 0.85
lineSpace = 16
color = 255,255,128,0
font = interface_normal
string = Controls

[TUTORIAL_CONTROLS_IMG]
position = 306,470,439,492
alignment = left
fontScale = 0.65
lineSpace = 12
font = KEYBOARD_SYMBOL

[TUTORIAL_SCROLL_TEXT]
command = click,select:TUTORIAL_INFO_TEXT
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 584,345,595,459
ownedcontrol = INFO_TEXT
rollerHeight = 11

[TUTORIAL_B_OK]
command = activate
command = deactivate,event:exitCancel
command = click
command = rightstep
position = 345,467,456,495
string = OK
glowoffset = 0,0

[TUTORIAL_B_OK2]
command = activate
command = deactivate,event:exitCancel
command = click
command = rightstep
position = 456,467,567,495
string = OK
glowoffset = 0,0

[TUTORIAL_CHECKBOX]
command = activate
command = deactivate,event:exitCancel
command = click
position = 700,562,927,579
alignment = left
iconoffset = 9,-2
iconsize = 20,20
individualpos = 0
section1 = 0,0,Show tutorial
fontScale = 1.0
normalFontColor = 255,255,255,255
selectFontColor = 255,255,255,255
normalpiccolor = 255,155,155,155
textClickable = 0
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; INFO_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[TUTORIAL_INFO_WINDOW]
show = 0
nodelist = TUTORIAL_FRAME_ZOOM,TUTORIAL_INFO_VIDEOZ,TUTORIAL_VFRAMEZ

[TUTORIAL_INFO_VIDEOZ]
position = 23,89,778,512
textureRect = 0,0,1.0,1.0
videoFile = Pirate.webm
color = 255,128,128,128
loop = 1
silent = 1

[TUTORIAL_FRAME_ZOOM]
position = 23,89,778,512
backimage = piclist=PAPER_FRAME, picname=paper, color=(245,50,50,50)
topline_height		= 2
bottomline_height	= 2
leftline_width		= 2
rightline_width		= 2

[TUTORIAL_VFRAMEZ]
position = 23,89,778,512
textureName = interfaces\empty_back.tga

