; This file contains battle interface images info

[CROSSHAIRS]
sTextureName    	= crosshairs.tga
wTextureWidth    	= 512
wTextureHeight    	= 256
picture = crosc11,0,0,32,32
picture = crosc12,32,0,64,32
picture = crosf11,66,0,128,64
picture = crosf12,128,0,192,64
picture = crosf21,192,0,256,64
picture = crosf22,256,0,320,64

[TUTORIAL_BACK1]
sTextureName   = ..\battle_interface\info_fader_t1.tga
wTextureWidth  = 1024
wTextureHeight = 256
picture = background,0,0,1024,256

[TUTORIAL_BACK2]
sTextureName   = ..\battle_interface\info_fader_t2.tga
wTextureWidth  = 1024
wTextureHeight = 512
picture = background,0,0,1024,512