;
; Recon Интерфейс "Игра в кости"
;

[MAIN]
item	= VIDEO,VIDEOBASE
item    = PICTURE,SCROLLPICT
item	= 100,pc,BUTTON,EXIT_BTN
item    = 200,BUTTON,B_PACK
item	= RECTANGLE,INF_RECT
item	= RECTANGLE,INF_STATS
item	= 100,PICTURE,ICON_1
item	= 100,PICTURE,ICON_2
item	= 100,PICTURE,ICON_GOLD
item	= FORMATEDTEXT,INFO_TEXT
item	= FORMATEDTEXT,STATS_TEXT
item	= FORMATEDTEXT,TIME_TEXT
item    = 200,BUTTON,B_ICON_1
item    = FORMATEDTEXT,B_TEXT_1
item    = 200,BUTTON,B_ICON_2

item    = 200,BUTTON,B_HeroDice1
item    = 200,BUTTON,B_HeroDice2
item    = 200,BUTTON,B_HeroDice3
item    = 200,BUTTON,B_HeroDice4
item    = 200,BUTTON,B_HeroDice5

item	= FORMATEDTEXT,STATS_WINS_TEXT
item	= FORMATEDTEXT,STATS_LOSES_TEXT
item	= FORMATEDTEXT,STATS_WINMONEY_TEXT
item	= FORMATEDTEXT,STATS_LOSEMONEY_TEXT
item	= FORMATEDTEXT,STATS_DIFF_TEXT
item	= FORMATEDTEXT,STATS_TIME_TEXT

[EXIT_BTN]
position	= 767,7,789,29
group		= ICONS_SPEC
picture		= exit button
command		= click,event:exitCancel
shadowColor	= 0,0,0,0

[SCROLLPICT]
bAbsoluteRectangle = 5
position	= 0,0,800,600
textureName	= interfaces\Recon\card_desk.tga

[B_PACK]
bBreakCommand	= 1
command		= click
position	= 553,78,708,225

[INF_RECT]
position	= 480,390,750,540
leftColor	= 205,255,255,255
topColor	= 128,50,30,30
rightColor	= 205,255,255,255
bottomColor	= 128,50,30,30

[INF_STATS]
position	= 763,230,919,380
leftColor	= 205,255,255,255
topColor	= 128,50,30,30
rightColor	= 205,255,255,255
bottomColor	= 128,50,30,30

[ICON_1]
position	= 710,392,748,430
textureName	= interfaces\money.tga

[ICON_2]
position	= 710,500,748,538
textureName	= interfaces\money.tga

[ICON_GOLD]
position	= 482,498,520,536
textureName	= interfaces\BoxImage.tga

[INFO_TEXT]
position	= 480,398,710,449
lineSpace	= 13
font		= interface_ultrasmall
fontScale	= 1

[STATS_TEXT]
position 	= 792,244,889,262
lineSpace 	= 13
font 		= interface_ultrasmall
fontScale 	= 1
alignment 	= center

[TIME_TEXT]
position 	= 768,210,917,228
lineSpace 	= 13
font 		= interface_normal
fontScale 	= 1
alignment 	= center

[B_ICON_1]
bBreakCommand	= 1
command		= click
position	= 710,392,748,430

[B_TEXT_1]
position	= 710,432,748,462
lineSpace	= 10
font		= interface_normal
fontScale	= 0.75
alignment	= center

[B_ICON_2]
bBreakCommand	= 1
command		= click
position	= 710,500,748,538

[B_HeroDice1]
bBreakCommand	= 1
command		= click
position	= 63,497,117,552

[B_HeroDice2]
bBreakCommand	= 1
command		= click
position	= 143,497,197,552

[B_HeroDice3]
bBreakCommand	= 1
command		= click
position	= 223,498,277,553

[B_HeroDice4]
bBreakCommand	= 1
command		= click
position	= 303,498,357,553

[B_HeroDice5]
bBreakCommand	= 1
command		= click
position	= 383,498,437,553

[STATS_WINS_TEXT]
position 	= 879,269,927,283
lineSpace 	= 13
font 		= interface_ultrasmall
fontScale 	= 1
alignment 	= left

[STATS_LOSES_TEXT]
position 	= 879,284,927,298
lineSpace	= 13
font 		= interface_ultrasmall
fontScale 	= 1
alignment 	= left

[STATS_WINMONEY_TEXT]
position 	= 879,299,927,313
lineSpace 	= 13
font 		= interface_ultrasmall
fontScale 	= 1
alignment 	= left

[STATS_LOSEMONEY_TEXT]
position 	= 879,314,927,329
lineSpace 	= 13
font 		= interface_ultrasmall
fontScale 	= 1
alignment 	= left

[STATS_DIFF_TEXT]
position 	= 879,329,927,344
lineSpace 	= 13
font 		= interface_ultrasmall
fontScale 	= 1
alignment 	= left

[STATS_TIME_TEXT]
position 	= 879,344,927,360
lineSpace 	= 13
font 		= interface_ultrasmall
fontScale 	= 1
alignment 	= left
