;
; Recon Интерфейс "Игра в карты"
;

[MAIN]
item = VIDEO,VIDEOBASE
item = PICTURE,SCROLLPICT
item = 100,pc,BUTTON,EXIT_BTN
item = 200,BUTTON,B_PACK
item = RECTANGLE,INF_RECT
item = RECTANGLE,INF_STATS
item = 100,PICTURE,ICON_1
item = 100,PICTURE,ICON_2
item = 100,PICTURE,ICON_GOLD
item = 100,PICTURE,ICON_CHECT
item = FORMATEDTEXT,INFO_TEXT
item = FORMATEDTEXT,STATS_TEXT
item = FORMATEDTEXT,TIME_TEXT
item = 200,BUTTON,B_ICON_1
item = FORMATEDTEXT,B_TEXT_1
item = FORMATEDTEXT,B_TEXT_2
item = 200,BUTTON,B_ICON_2
item = FORMATEDTEXT,STATS_WINS_TEXT
item = FORMATEDTEXT,STATS_LOSES_TEXT
item = FORMATEDTEXT,STATS_WINMONEY_TEXT
item = FORMATEDTEXT,STATS_LOSEMONEY_TEXT
item = FORMATEDTEXT,STATS_DIFF_TEXT
item = FORMATEDTEXT,STATS_TIME_TEXT

[EXIT_BTN]
position = 767,8,789,30
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
shadowColor = 0,0,0,0

[SCROLLPICT]
bAbsoluteRectangle = 5
position = 0,0,800,600
textureName = interfaces\Recon\card_desk.tga

[B_PACK]
bBreakCommand = 1
command = click
position = 80,205,195,375

[INF_RECT]
position = 493,228,763,380
leftColor = 205,255,255,255
topColor = 128,50,30,30
rightColor = 205,255,255,255
bottomColor = 128,50,30,30

[INF_STATS]
position = 763,230,919,380
leftColor = 205,255,255,255
topColor = 128,50,30,30
rightColor = 205,255,255,255
bottomColor = 128,50,30,30

[ICON_1]
position = 496,232,534,270
textureName = interfaces\money.tga

[ICON_2]
position = 496,338,534,376
textureName = interfaces\money.tga

[ICON_GOLD]
position = 710,340,748,378
textureName = interfaces\BoxImage.tga

[ICON_CHECT]
position = 708,284,750,326
textureName = interfaces\gold.tga

[INFO_TEXT]
position = 540,238,756,289
lineSpace = 13
font = interface_ultrasmall
fontScale = 1

[STATS_TEXT]
position = 792,244,889,262
lineSpace = 13
font = interface_ultrasmall
fontScale = 1
alignment = center

[TIME_TEXT]
position = 768,210,917,228
lineSpace = 13
font = interface_normal
fontScale = 1
alignment = center

[B_ICON_1]
bBreakCommand = 1
command = click
position = 496,232,534,270

[B_TEXT_1]
position = 496,272,534,302
lineSpace = 10
font = interface_normal
fontScale = 0.75
alignment = center

[B_TEXT_2]
position = 390,368,412,383
lineSpace = 10
font = interface_normal
fontScale = 1.0
alignment = center

[B_ICON_2]
bBreakCommand = 1
command = click
position = 496,340,534,378

[STATS_WINS_TEXT]
position = 879,269,927,283
lineSpace = 13
font = interface_ultrasmall
fontScale = 1
alignment = left

[STATS_LOSES_TEXT]
position = 879,284,927,299
lineSpace = 13
font = interface_ultrasmall
fontScale = 1
alignment = left

[STATS_WINMONEY_TEXT]
position = 879,299,927,314
lineSpace = 13
font = interface_ultrasmall
fontScale = 1
alignment = left

[STATS_LOSEMONEY_TEXT]
position = 879,314,927,329
lineSpace = 13
font = interface_ultrasmall
fontScale = 1
alignment = left

[STATS_DIFF_TEXT]
position = 879,329,927,344
lineSpace = 13
font = interface_ultrasmall
fontScale = 1
alignment = left

[STATS_TIME_TEXT]
position = 879,344,927,360
lineSpace = 13
font = interface_ultrasmall
fontScale = 1
alignment = left

