; boal 15.01.06 FrameForm
[MAIN]
item    = PICTURE,LOADING_PICTURE
item	= FORMATEDTEXT,INFO_TEXT

[LOADING_PICTURE]
bAbsoluteRectangle = 5
position = 0,0,800,600
textureName	= interfaces\FrameForm.tga

[INFO_TEXT]
position		= 60,50,740,550
lineSpace		= 35
font			= INTERFACE_QUEST_TEXT
fontScale		= 1.2

