; Recon - Интерфейс "Орудия"

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 15,VIDEORECTANGLE,V_TG
item = 25,SLIDEPICTURE,DUST
;
item = 30,FRAME,MAIN_FRAME
item = 35,FORMATEDTEXT,MAIN_CAPTION
item = 35,pc,BUTTON,EXIT_BTN
;
item = 50,PICTURE,MAIN_CHARACTER_PICTURE
item = 50,PICTURE,OTHER_PICTURE
item = 55,PICTURE,BORDER_PICTURE_1
item = 55,PICTURE,BORDER_PICTURE_2
item = 55,FORMATEDTEXT,CAPACITY
item = 50,FORMATEDTEXT,STORE_CAPACITY
item = 55,FORMATEDTEXT,OUR_GOLD
item = 50,SCROLLIMAGE,SHIPS_SCROLL
item = 55,BUTTON,LEFTSCROLLBUTTON
item = 55,BUTTON,RIGHTSCROLLBUTTON
item = 55,CHECKBUTTON,TRADEASSISTANT_CHECKBOX
;
item = 50,TABLE,TABLE_LIST
item = 55,SCROLLER,SCROLL_LIST
;
;  BOX_MOVE
item = 100,FRAME,QTY_FRAME
item = 150,FORMATEDTEXT,QTY_WINDOW_FIX
item = 150,FORMATEDTEXT,QTY_CAPTION
item = 150,PICTURE,QTY_GOODS_PICTURE
item = 150,FORMATEDTEXT,QTY_GOODS_INFO
item = 150,FORMATEDTEXT,QTY_RESULT
item = 155,PCEDITBOX,QTY_EDIT
item = 150,VIDEO,V_QTY_EDIT
item = 150,BUTTON,QTY_ADD_BUTTON
item = 150,BUTTON,QTY_REMOVE_BUTTON
item = 150,BUTTON,QTY_ADD_ALL_BUTTON
item = 150,BUTTON,QTY_REMOVE_ALL_BUTTON
item = 150,FORMATEDTEXT,QTY_INFO_SHIP_QTY
item = 150,FORMATEDTEXT,QTY_INFO_STORE_QTY
item = 150,FORMATEDTEXT,QTY_INFO_SHIP_PRICE
item = 150,FORMATEDTEXT,QTY_INFO_STORE_PRICE
item = 150,TEXTBUTTON2,QTY_OK_BUTTON
item = 150,TEXTBUTTON2,QTY_CANCEL_BUTTON
item = WINDOW,QTY_WINDOW
;
start = TABLE_LIST

[MAIN_BACK]
bAbsoluteRectangle = 0
position = -134,0,933,600
textureName = interfaces\Recon\bgr_cannons.tga

[V_TG]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

; анимация (крутится)
[DUST]
position 	= -200,-300,1000,1000
techniqueName	= iRotate
textureName	= interfaces\Recon\dust.tga
textureRect	= 0,0,1.0,1.0
color		= 200,200,200,200
rotate		= -0.03,0.005
speed		= 6000,0.0,0

[MAIN_FRAME]
captionheight = 24
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
position = 100,10,700,590
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(190,128,128,128)

[MAIN_CAPTION]
position = 100,14,700,34
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255,255,255,200

[EXIT_BTN]
position = 675,14,695,34
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
command = deactivate,event:exitCancel
shadowColor = 0,0,0,0
bShowGlowCursor = 0
shadowoffset = -1,-1

[MAIN_CHARACTER_PICTURE]
position = 110,44,165,99
textureName = interfaces\portraits\128\face_1.tga

[OTHER_PICTURE]
position = 635,44,690,99
textureName = interfaces\shipyard.tga

[BORDER_PICTURE_1]
textureName = interfaces\emptyborder.tga
position = 110,44,165,99

[BORDER_PICTURE_2]
textureName = interfaces\emptyborder.tga
position = 635,44,690,99

[CAPACITY]
position = 165,44,255,99
fontScale = 0.85
lineSpace = 16
alignment = center
Color = 255,255,255,255

[STORE_CAPACITY]
position = 545,44,635,99
fontScale = 0.85
lineSpace = 16
alignment = center
Color = 255,255,255,255

[OUR_GOLD]
position = 128,567,392,582
fontScale = 0.9
lineSpace = 15
alignment = center
Color = 255,255,255,156

[SHIPS_SCROLL]
command = activate
command = deactivate,event:ExitCancel
command = upstep,select:TABLE_LIST
command = downstep,select:TABLE_LIST
command = rightstep
command = leftstep
command = speedright
command = speedleft
command = click,select:SHIPS_SCROLL
position = 255,44,545,99
imageSize = 55,55
wDelta = 3
glowoffset = 0,0

[LEFTSCROLLBUTTON]
command = activate,select:SHIPS_SCROLL,com:speedleft:SHIPS_SCROLL
command = click,select:SHIPS_SCROLL,com:leftstep:SHIPS_SCROLL,com:activate:LEFTSCROLLBUTTON
position = 340,49,375,94
group = ICONS
picture = left arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[RIGHTSCROLLBUTTON]
command = activate,select:SHIPS_SCROLL,com:speedright:SHIPS_SCROLL
command = click,select:SHIPS_SCROLL,com:rightstep:SHIPS_SCROLL,com:activate:RIGHTSCROLLBUTTON
position = 425,49,460,94
group = ICONS
picture = right arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[TABLE_LIST]
command = deactivate,event:exitCancel
command = click,select:TABLE_LIST
command = rclick,event:ShowHelpHint,select:TABLE_LIST
command = dblclick,event:ShowItemInfo,select:TABLE_LIST
command = activate,event:ShowItemInfo
command = upstep
command = downstep
command = rightstep,com:click:QTY_REMOVE_BUTTON
command = leftstep,com:click:QTY_ADD_BUTTON
command = speedright,com:click:QTY_REMOVE_ALL_BUTTON
command = speedleft,com:click:QTY_ADD_ALL_BUTTON
position = 100,109,682,560
scroller = SCROLL_LIST
rowquantity = 15
colquantity = 9
fontcellvalignment = center
fontcellscale = 0.9
colswidth = 55,50,50,174,50,50,50,55,55
rowsheight = 44,29,29,29,29,29,29,29,29,29,29,29,29,29,29
NormalLineHeight = 29

[SCROLL_LIST]
command = click, select:TABLE_LIST
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 690,109,700,560
ownedcontrol = TABLE_LIST

[QTY_WINDOW]
show = 0
nodelist = QTY_FRAME,QTY_EDIT,V_QTY_EDIT,QTY_OK_BUTTON,QTY_CANCEL_BUTTON,QTY_GOODS_INFO,QTY_GOODS_PICTURE
nodelist = QTY_CAPTION,QTY_ADD_BUTTON,QTY_REMOVE_BUTTON,QTY_ADD_ALL_BUTTON,QTY_REMOVE_ALL_BUTTON
nodelist = QTY_INFO_STORE_QTY,QTY_INFO_SHIP_QTY,QTY_INFO_SHIP_PRICE,QTY_INFO_STORE_PRICE,QTY_RESULT,QTY_WINDOW_FIX

[QTY_FRAME]
captionheight = 24
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
position = 150,200,650,490
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(255,150,150,150)

[QTY_WINDOW_FIX]
command = click,event:None
command = activate,event:None
position = 150,200,650,489

[QTY_CAPTION]
position = 200,202,600,222
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255,255,255,200

[QTY_GOODS_PICTURE]
position = 160,235,240,315
bShowGlowCursor = 0

[QTY_GOODS_INFO]
position = 240,229,585,390
fontScale = 0.85
lineSpace = 15
alignment = center

[QTY_RESULT]
position = 310,385,490,415
fontScale = 0.9
lineSpace = 15
alignment = center
Color = 255,255,255,156

[QTY_EDIT]
command = click,select:QTY_EDIT
command = deactivate,event:exitCancel
command = activate,event:confirmChangeQTY_EDIT
position = 370,415,430,440
strFont = interface_button
argbFontColor = 255,255,255,255
stringLength = 5
stringWidth = 80
stringalign = center
stringoffset = 9,4
MiddleImage = color=(0,128,128,128), piclist=MAIN_ICONS, picname=middle side button
excludechars = qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM ёйцукенгшщзхъфывапролджэячсмитьбю	ЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ!@#№$%^&*()_-+=~`'"|\/?:;<>,.{}[]

[V_QTY_EDIT]
bAbsoluteRectangle = 0
position = 370,415,430,440
sTexture = bigbutton
color = 120,60,80,70

[QTY_ADD_ALL_BUTTON]
command = click,event:ADD_ALL_BUTTON
group = ARROWS
picture = left_all
position = 310,415,335,440
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_ADD_BUTTON]
command = click,event:ADD_BUTTON
group = ARROWS
picture = left
position = 335,415,360,440
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_REMOVE_BUTTON]
command = click,event:REMOVE_BUTTON
group = ARROWS
picture = right
position = 440,415,465,440
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_REMOVE_ALL_BUTTON]
command = click,event:REMOVE_ALL_BUTTON
group = ARROWS
picture = right_all
position = 465,415,490,440
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_INFO_SHIP_PRICE]
position = 210,385,300,415
fontScale = 0.9
lineSpace = 15
alignment = center
Color = 255,255,255,156

[QTY_INFO_STORE_PRICE]
position = 500,385,590,415
fontScale = 0.9
lineSpace = 15
alignment = center
Color = 255,255,255,156

[QTY_INFO_SHIP_QTY]
position = 210,420,300,435
fontScale = 1.1
lineSpace = 15
alignment = center

[QTY_INFO_STORE_QTY]
position = 500,420,590,435
fontScale = 1.1
lineSpace = 15
alignment = center

[QTY_OK_BUTTON]
command = activate
command = click,event:TransactionOK
command = deactivate,event:MouseRClickUP
command = rightstep,com:click:QTY_REMOVE_BUTTON
command = leftstep,com:click:QTY_ADD_BUTTON
command = speedright,com:click:QTY_REMOVE_ALL_BUTTON
command = speedleft,com:click:QTY_ADD_ALL_BUTTON
position = 290,450,390,475
string = Ok
fontScale = 0.85
glowoffset = 0,0

[QTY_CANCEL_BUTTON]
command = activate
command = click,event:exitCancel
command = deactivate,event:exitCancel
command = rightstep,com:click:QTY_REMOVE_BUTTON
command = leftstep,com:click:QTY_ADD_BUTTON
command = speedright,com:click:QTY_REMOVE_ALL_BUTTON
command = speedleft,com:click:QTY_ADD_ALL_BUTTON
position = 410,450,510,475
string = Cancel
fontScale = 0.85
glowoffset = 0,0

[TRADEASSISTANT_CHECKBOX]
command = click
command = select:TRADEASSISTANT_CHECKBOX
position = 479,567,614,582
alignment = center
iconsize = 15,15
individualpos = 1
rect_textoffset = 25,0,0,0
section1 = 0,0,Trade Assistant
fontScale = 0.85
bShowGlowCursor = 0
