; ReCon Интерфейс "Навыки персонажа в таверне"

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 20,VIDEORECTANGLE,V_CHARACTER
item = 10,SLIDEPICTURE,DUST
item = 20,VIDEORECTANGLE,V_SAVELOAD
item = 100,pc,BUTTON,EXIT_BTN
item = 100,TITLE,TITLE

item = 400,IMAGECOLLECTION,BORDERS
item = 200,PICTURE,CHARACTER_BIG_PICTURE
item = 205,FRAME,CHARACTER_FRAME
item = 201,STATUSLINE,LOYALITY
item = 505,FORMATEDTEXT,LOYALITY_STR
item = 200,TABLE,TABLE_SPECIAL
item = 200,TABLE,TABLE_SKILL_1
item = 200,TABLE,TABLE_SKILL_2
item = 200,TABLE,TABLE_PERKS
item = 200,TABLE,TABLE_OTHER
item = 201,SCROLLER,SCROLL_PERKS
item = 504,FORMATEDTEXT,HERO_NAME
item = 504,FORMATEDTEXT,STR_1
item = 504,FORMATEDTEXT,STR_2
item = 504,FORMATEDTEXT,STR_3
item = 504,FORMATEDTEXT,STR_4
item = 120,PICTURE,TABBTN_1
item = 125,FORMATEDTEXT,TABSTR_1
item = 120,PICTURE,TABBTN_2
item = 125,FORMATEDTEXT,TABSTR_2
item = 125,TEXTBUTTON2,PERK_BTN
item = 125,TEXTBUTTON2,TRAIT_BTN
item = 505,STATUSLINE,BAR_REPUTATION
item = 505,STATUSLINE,BAR_HEALTH
item = 505,BUTTON,B_SKILLUP
item = 505,BUTTON,B_SKILLDOWN
item = 555,TEXTBUTTON2,GAME_ACCEPT
item = 555,TEXTBUTTON2,GAME_CANCEL
item = WINDOW,MAIN_WINDOW

item = 553,RECTANGLE,PERK_FADER
item = 554,SLIDEPICTURE,PERK_DUST
item = 555,FRAME,PERK_WINDOW_FRAME
item = 555,TEXTBUTTON2,PERK_ACCEPT
item = 555,TEXTBUTTON2,PERK_CANCEL
item = 555,FORMATEDTEXT,PERK_WINDOW_CAPTION
item = 555,FORMATEDTEXT,PERK_WINDOW_TEXT
item = 555,FORMATEDTEXT,PERK_TEXT_FREE
item = 555,pc,BUTTON,PERK_EXIT_BTN
item = 555,PICTURE,PERK_PICTURE
item = 556,PICTURE,PERK_ON
item = 555,TABLE, PERK_TABLE_NEED
item = WINDOW,PERK_WINDOW

item = 553,RECTANGLE,MSG_FADER
item = 554,SLIDEPICTURE,MSG_DUST
item = 555,FRAME,MSG_WINDOW_FRAME
item = 555,TEXTBUTTON2,MSG_OK
item = 555,FORMATEDTEXT,MSG_WINDOW_CAPTION
item = 555,FORMATEDTEXT,MSG_WINDOW_TEXT
item = WINDOW,MSG_WINDOW

[FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 150,0,0,0
topColor = 150,0,0,0
rightColor = 150,0,0,0
bottomColor = 150,0,0,0
borderColor = 0,0,0,0

[MAIN_BACK]
bAbsoluteRectangle = 0
position = -134,0,933,600
textureName = interfaces\Recon\character_list.tga

[DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[V_CHARACTER]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[TITLE]
position = 0,25,800,60
stringOffset = 6
stringWidth = 220

[EXIT_BTN]
position = 700,34,720,52
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
shadowColor = 0,0,0,0

[MAIN_WINDOW]
show = 1
nodelist = CHARACTER_BIG_PICTURE,HERO_NAME,STR_1,STR_2,STR_3,STR_4,TABBTN_1,TABSTR_1,TABBTN_2,TABSTR_2
nodelist = LOYALITY_STR,LOYALITY,SUBSTRATE,SCROLL_PERKS,BAR_REPUTATION,BAR_HEALTH
nodelist = TABLE_SPECIAL,TABLE_SKILL_1,TABLE_SKILL_2,TABLE_PERKS,TABLE_OTHER,TABSTR_1,TABSTR_2,B_SKILLUP,B_SKILLDOWN

[B_SKILLUP]
group = ICONS
bBreakCommand = 1
command = click
command = rclick
position = 572,45,602,73
picture = right arrow

[B_SKILLDOWN]
group = ICONS
bBreakCommand = 1
command = click
command = rclick
position = 542,45,572,73
picture = left arrow

[BORDERS]
groupName = RECON_ICONS
; S.P.E.C.I.A.L.
picture = border topleft,col:{255,128,128,128},pos:{80,60,90,70}
picture = border topright,col:{255,128,128,128},pos:{280,60,290,70}
; умения 1 оконо
picture = border topleft,col:{255,128,128,128},pos:{510,60,520,70}
picture = border topright,col:{255,128,128,128},pos:{710,60,720,70}
; умения 2 оконо
picture = border topleft,col:{255,128,128,128},pos:{510,320,520,330}
picture = border topright,col:{255,128,128,128},pos:{710,320,720,330}

[CHARACTER_BIG_PICTURE]
position = 295,84,505,294
textureName = interfaces\portraits\256\face_1.tga

[HERO_NAME]
position = 295,63,505,85
lineSpace = 19
font = INTERFACE_TITLE
fontScale = 0.9

[CHARACTER_FRAME]
captionheight = 25
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = 295,60,505,310
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(0,128,128,128)
color = 255,128,128,128
lefttop_size = 12,12
righttop_size = 12,12
leftbottom_size = 12,12
rightbottom_size = 12,12
topline_height = 2
bottomline_height = 2
leftline_width = 2
rightline_width = 2

[LOYALITY]
position = 297,292,503,308

[LOYALITY_STR]
command = deactivate,event:exitCancel
command = click
command = rclick,select:LOYALITY_STR,event:ShowInfoWindow
position = 295,295,505,306
lineSpace = 10
fontScale = 0.65
font = interface_normal
string = Loyality
color = 180,255,255,255
bShowGlowCursor = 0

[TABLE_SPECIAL]
command = click,select:TABLE_SPECIAL
command = rclick,select:TABLE_SPECIAL,event:ShowInfoWindow
command = deactivate,event:exitCancel
command = upstep
command = downstep
position = 80,60,290,270
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(235,128,128,128)
vlinewidth = 0
hlineheight = 1
rowquantity = 8
colquantity = 4
fontcellvalignment = center
fontcellalignment = left
colswidth = 30,120,30,30
rowsheight = 25,27,26,26,26,26,26,27
NormalLineHeight = 26
fontlist1 = INTERFACE_MENU
fontlist2 = bold_numbers

[TABLE_PERKS]
command = click,select:TABLE_PERKS
command = rclick,select:TABLE_PERKS,event:ShowInfoWindow
command = dblclick,select:TABLE_PERKS,event:ChoosePerk
command = deactivate,event:exitCancel
command = upstep
command = downstep
position = 80,330,280,570
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(235,128,128,128)
scroller = SCROLL_PERKS
vlinewidth = 0
hlineheight = 1
rowquantity = 8
colquantity = 2
fontcellvalignment = center
colswidth = 32,167
rowsheight = 29,30,30,30,30,30,30,30
NormalLineHeight = 32

[TABLE_SKILL_1]
command = click,select:TABLE_SKILL_1
command = rclick,select:TABLE_SKILL_1,event:ShowInfoWindow
command = deactivate,event:exitCancel
command = upstep
command = downstep
position = 510,60,720,310
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(235,128,128,128)
vlinewidth = 0
hlineheight = 1
rowquantity = 8
colquantity = 6
fontcellvalignment = center
colswidth = 32,85,30,30,30,2
rowsheight = 25,32,32,32,32,32,32,32
NormalLineHeight = 32
fontlist1 = bold_numbers

[TABLE_SKILL_2]
command = click,select:TABLE_SKILL_2
command = rclick,select:TABLE_SKILL_2,event:ShowInfoWindow
command = deactivate,event:exitCancel
command = upstep
command = downstep
position = 510,320,720,570
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(235,128,128,128)
vlinewidth = 0
hlineheight = 1
rowquantity = 8
colquantity = 6
fontcellvalignment = center
colswidth = 32,85,30,30,30,2
rowsheight = 25,32,32,32,32,32,32,32
NormalLineHeight = 32
fontlist1 = bold_numbers

[SCROLL_PERKS]
command = click, select:TABLE_PERKS
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 280,330,290,570
begEndBaseSize = 12
rollerHeight = 12
ownedcontrol = TABLE_PERKS

[TABLE_OTHER]
command = click,select:TABLE_OTHER
command = rclick,select:TABLE_OTHER,event:ShowInfoWindow
command = deactivate,event:exitCancel
command = upstep
command = downstep
position = 295,320,510,570
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(235,128,128,128)
vlinewidth = 0
hlineheight = 1
rowquantity = 9
colquantity = 3
fontcellvalignment = center
colswidth = 35,85,89
rowsheight = 28,28,28,27,27,27,28,28,28
NormalLineHeight = 29

[STR_1]
position = 80,63,290,85
lineSpace = 19
font = INTERFACE_TITLE
fontScale = 0.9

[STR_2]
position = 510,63,720,85
lineSpace = 19
font = INTERFACE_TITLE
fontScale = 0.9

[STR_3]
position = 510,323,720,345
lineSpace = 19
font = INTERFACE_TITLE
fontScale = 0.9

[STR_4]
position = 80,308,280,330
lineSpace = 19
font = INTERFACE_TITLE
fontScale = 0.9

[BAR_HEALTH]
position = 336,399,412,402

[BAR_REPUTATION]
position = 336,480,412,483

[TABBTN_1]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = rclick,select:TABBTN_1,event:ShowInfoWindow
position = 80,305,183,331
groupName = TABS
picName = TabDeSelected
bShowGlowCursor = 0

[TABSTR_1]
position = 80,311,183,331
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Personal_abilities

[TABBTN_2]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = rclick,select:TABBTN_2,event:ShowInfoWindow
position = 187,305,290,331
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_2]
position = 187,311,290,331
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Ship_abilities

[PERK_BTN]
bBreakCommand = 1
command = activate
command = click,event:ShowPerks
command = deactivate,event:exitCancel
position = 80,277,185,304
unselectableFontColor = 255,255,255,255
fontColor = 255,128,128,128
string = Abilities
strOffset = 3.7
glowoffset = 0,0

[TRAIT_BTN]
bBreakCommand = 1
command = activate
command = click,event:ShowTraits
command = deactivate,event:exitCancel
position = 185,277,290,304
unselectableFontColor = 255,255,255,255
fontColor = 255,128,128,128
string = Traits
strOffset = 3.7
glowoffset = 0,0


[MSG_WINDOW]
show = 0
nodelist = MSG_FADER,MSG_DUST,MSG_OK,MSG_WINDOW_FRAME,MSG_WINDOW_CAPTION,MSG_WINDOW_TEXT

[MSG_WINDOW_CAPTION]
position = 180,188,620,210
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center

[MSG_WINDOW_TEXT]
command = click
position = 190,220,610,340
fontScale = 1.0
lineSpace = 20
alignment = center
Color = 255,255,255,255

[MSG_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[MSG_DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[MSG_OK]
bBreakCommand = 1
command = activate,event:ExitMsgMenu
command = click,event:ExitMsgMenu
command = deactivate,event:ExitMsgMenu
position = 320,345,480,375
string = Ok
glowoffset = 0,0

[MSG_WINDOW_FRAME]
captionheight = 25
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = 180,185,620,380

[PERK_WINDOW]
show = 0
nodelist = PERK_FADER,PERK_DUST,PERK_ACCEPT,PERK_CANCEL,PERK_WINDOW_FRAME,PERK_WINDOW_CAPTION,PERK_WINDOW_TEXT,PERK_EXIT_BTN
nodelist = PERK_PICTURE,PERK_ON,PERK_TABLE_NEED,PERK_TEXT_FREE

[PERK_TABLE_NEED]
command = click,select:PERK_TABLE_NEED
command = deactivate,event:ExitPerkMenu
command = rclick,select:PERK_TABLE_NEED,event:ShowInfoWindow
command = upstep
command = downstep
position = 187,310,317,405
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(0,128,128,128)
vlinewidth = 0
hlineheight = 1
borderwidth = 0
bordercornersize = 0,0
rowquantity = 4
colquantity = 2
fontcellvalignment = center
fontcellalignment = center
selectimage = color=(0,128,48,48)
colswidth = 27,102
rowsheight = 1,30,30,30
NormalLineHeight = 28
fontlist1 = INTERFACE_TITLE

[PERK_ON]
position = 196,193,304,301
textureName = interfaces\usedflag.tga

[PERK_PICTURE]
position = 196,193,304,301
textureName = interfaces\portraits\256\face_1.tga

[PERK_WINDOW_CAPTION]
command = click
bAbsoluteRectangle = 5
position = 247,162,555,194
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255, 255, 255, 255
backoffset = 1, 2, 0, -2
string = Abilities

[PERK_TEXT_FREE]
command = click
position = 310,383,618,415
fontScale = 1.0
lineSpace = 20
alignment = center

[PERK_WINDOW_TEXT]
command = click
position = 312,197,614,382
fontScale = 0.85
lineSpace = 16
alignment = center
valignment = 1
Color = 255, 255, 255, 255

[PERK_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[PERK_DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[PERK_ACCEPT]
bBreakCommand = 1
command = activate
command = click,event:AcceptPerk
command = deactivate,event:ExitPerkMenu
position = 245,412,395,444
string = Accept
glowoffset = 0,0

[PERK_CANCEL]
bBreakCommand = 1
command = activate
command = click,event:ExitPerkMenu
command = deactivate,event:ExitPerkMenu
position = 405,412,555,444
string = Cancel
glowoffset = 0,0

[PERK_WINDOW_FRAME]
position = 179,156,624,455
captionheight = 28
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captionoffset = 0,0,0,0
captiondividerheight = 1
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(255,150,150,150)

[PERK_EXIT_BTN]
position = 596,160,618,182
group = ICONS_SPEC
picture = exit button
command = click,event:ExitPerkMenu
shadowColor = 0,0,0,0

[GAME_ACCEPT]
bBreakCommand = 1
command = activate
command = click,event:exitCancel
command = deactivate,event:exitCancel
position = 282,572,392,597
string = Ok
fontscale = 0.8
glowoffset = 0,0

[GAME_CANCEL]
bBreakCommand = 1
command = activate
command = click,event:exitCancel
command = deactivate,event:exitCancel
position = 416,572,526,597
string = Cancel
fontscale = 0.8
glowoffset = 0,0

