; ReCon Интерфейс "Энцииклопедия".

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 15,VIDEORECTANGLE,V_MAPVIEW
item = 10,SLIDEPICTURE,DUST
item = 35,TITLE,TITLE
item = 35,BUTTON,EXIT_BTN
;
item = 100,TABLE,TABLE_PAGES
item = 100,PICTURE,FRAME_DESCRIBE
item = 101,FORMATEDTEXT,PAGE_DESCRIBE
;
item = 100,STRINGCOLLECTION,PAGES_TEXT
item = 100,PICTURE,PAGE_1
item = 100,PICTURE,PAGE_2
item = 100,PICTURE,PAGE_3
item = 100,PICTURE,PAGE_4
item = 100,PICTURE,PAGE_5
item = 101,FORMATEDTEXT,PAGE_NUM_1
item = 101,FORMATEDTEXT,PAGE_NUM_2
item = 101,FORMATEDTEXT,PAGE_NUM_3
item = 101,FORMATEDTEXT,PAGE_NUM_4
item = 101,FORMATEDTEXT,PAGE_NUM_5
;
item = WINDOW,MAIN_WINDOW
;
start = TITLE

[MAIN_WINDOW]
show = 1
nodelist = TITLE,EXIT_BTN
nodelist = TABLE_PAGES,PAGE_DESCRIBE

[TABLE_PAGES]
command = deactivate,event:exitCancel
command = click,select:TABLE_PAGES
command = rclick,select:TABLE_PAGES,event:ShowInfoWindow
command = upstep
command = downstep
fontcellcolor = 255,255,255,255
fontcellalignment = center
fontcellvalignment = center
fontlist1 = INTERFACE_TITLE
fontlist2 = INTERFACE_NORMAL
position = 615,140,780,464
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(255,128,128,128)
vlinewidth = 2
hlineheight = 1
hlineisbreakable = 1
borderwidth = 1
rowquantity = 13
colquantity = 1
colswidth = 164
rowsheight = 27,27,27,27,27,27,27,27,27,27,27,27,27
NormalLineHeight = 27

[PAGE_DESCRIBE]
position = 120,314,520,446
lineSpace = 19
font = INTERFACE_QUEST_TEXT
fontScale = 0.85

[MAIN_BACK]
bAbsoluteRectangle = 0
;position = -134,0,933,600
position = -169,-269,969,869
textureName = interfaces\Recon\bgr_interface.tga

[DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[V_MAPVIEW]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[TITLE]
position = 0,100,800,135
stringOffset = 6
stringWidth = 220

[EXIT_BTN]
position = 759,107,779,125
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
shadowColor = 0,0,0,0
bShowGlowCursor = 0

[PAGE_1]
position = 86,222,150,286
textureName = interfaces\perks\NotAvailable.tga
command = click,event:ShowPage1

[PAGE_2]
position = 186,222,250,286
textureName = interfaces\perks\NotAvailable.tga
command = click,event:ShowPage2

[PAGE_3]
position = 286,222,350,286
textureName = interfaces\perks\NotAvailable.tga
command = click,event:ShowPage3

[PAGE_4]
position = 386,222,450,286
textureName = interfaces\perks\NotAvailable.tga
command = click,event:ShowPage4

[PAGE_5]
position = 486,222,550,286
textureName = interfaces\perks\NotAvailable.tga
command = click,event:ShowPage5

[PAGES_TEXT]
string = Page 1,font:INTERFACE_QUEST_TEXT,pos:{118,203},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.85,state:{CS}
string = Page 2,font:INTERFACE_QUEST_TEXT,pos:{218,203},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.85,state:{CS}
string = Page 3,font:INTERFACE_QUEST_TEXT,pos:{318,203},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.85,state:{CS}
string = Page 4,font:INTERFACE_QUEST_TEXT,pos:{418,203},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.85,state:{CS}
string = Page 5,font:INTERFACE_QUEST_TEXT,pos:{518,203},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.85,state:{CS}

[PAGE_NUM_1]
position = 126,262,151,287
font = INTERFACE_NORMAL
fontScale = 1.2
lineSpace = 16

[PAGE_NUM_2]
position = 226,262,251,287
font = INTERFACE_NORMAL
fontScale = 1.2
lineSpace = 16

[PAGE_NUM_3]
position = 326,262,351,287
font = INTERFACE_NORMAL
fontScale = 1.2
lineSpace = 16

[PAGE_NUM_4]
position = 426,262,451,287
font = INTERFACE_NORMAL
fontScale = 1.2
lineSpace = 16

[PAGE_NUM_5]
position = 526,262,551,287
font = INTERFACE_NORMAL
fontScale = 1.2
lineSpace = 16

[FRAME_DESCRIBE]
position = 15,140,614,492
textureName = interfaces\Recon\questbook_paper.tga
color = 255,255,255,255

