;
; Recon Окно найма матросов в таверне
;

[MAIN]
item = 80,RECTANGLE,FADER
item = 81,SLIDEPICTURE,DUST
item = 82,FRAME,MAIN_FRAME
item = 83,SCROLLIMAGE,SHIPS_SCROLL
item = 110,FORMATEDTEXT,TITLE_MAIN
item = 110,pc,BUTTON,EXIT_BTN
item = 130,BUTTON,LEFTSCROLLBUTTON
item = 130,BUTTON,RIGHTSCROLLBUTTON
item = 85,PICTURE,MAIN_CHARACTER_PICTURE
item = 85,PICTURE,OTHER_PICTURE
item = 86,PICTURE,BORDER_PICTURE_1
item = 86,PICTURE,BORDER_PICTURE_2
item = 90,FORMATEDTEXT,OUR_GOLD
item = 200,FORMATEDTEXT,FOOD_SHIP
item = 200,FORMATEDTEXT,MONEY_SHIP
item = 200,FORMATEDTEXT,INFO_SHIP
item = 200,FORMATEDTEXT,TAVERN_PRICE
;; 1
item = 400,PICTURE,CREW_PICTURE
item = 504,FORMATEDTEXT,CREW_QTY
item = 403,PICTURE,CREW_MORALE_PIC
item = 200,TABLE,TABLE_CREW
item = 403,FORMATEDTEXT,CREW_MORALE_TEXT
item = 400,STATUSLINE,BAR_Sailors
item = 400,STATUSLINE,BAR_Cannoners
item = 400,STATUSLINE,BAR_Soldiers
;; 2
item = 400,PICTURE,CREW_PICTURE2
item = 504,FORMATEDTEXT,CREW_QTY2
item = 403,PICTURE,CREW_MORALE_PIC2
item = 200,TABLE,TABLE_CREW2
item = 403,FORMATEDTEXT,CREW_MORALE_TEXT2
item = 400,STATUSLINE,BAR_Sailors2
item = 400,STATUSLINE,BAR_Cannoners2
item = 400,STATUSLINE,BAR_Soldiers2
item = WINDOW,MAIN_WINDOW
;;;
item = 600,FORMATEDTEXT,QTY_TypeOperation
item = 600,FORMATEDTEXT,QTY_Result
item = 599,VIDEO,V_QTY_EDIT
item = 600,PCEDITBOX,QTY_EDIT
item = 600,BUTTON,QTY_ADD_BUTTON
item = 600,BUTTON,QTY_REMOVE_BUTTON
item = 600,BUTTON,QTY_ADD_ALL_BUTTON
item = 600,BUTTON,QTY_REMOVE_ALL_BUTTON
item = 600,TEXTBUTTON2,QTY_OK_BUTTON
item = 600,TEXTBUTTON2,QTY_CANCEL_BUTTON

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SALARY_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 700,RECTANGLE,SALARY_REQUIREMENT_FADER
item = 700,FRAME,SALARY_REQUIREMENT_FRAME
item = 700,TEXTBUTTON2,SALARY_REQUIREMENT_ACCEPT
item = 700,TEXTBUTTON2,SALARY_REQUIREMENT_CANCEL
item = 700,FORMATEDTEXT,SALARY_REQUIREMENT_CAPTION
item = 700,FORMATEDTEXT,SALARY_REQUIREMENT_WINDOW_TEXT
item = 700,pc,BUTTON,SALARY_REQUIREMENT_EXIT
item = WINDOW,SALARY_REQUIREMENT_WINDOW

[MAIN_WINDOW]
show = 1
nodelist = V_QTY_EDIT,FADER,DUST,QTY_TypeOperation,QTY_Result,QTY_EDIT,QTY_ADD_BUTTON,QTY_ADD_ALL_BUTTON,QTY_REMOVE_ALL_BUTTON,QTY_REMOVE_BUTTON,QTY_OK_BUTTON,QTY_CANCEL_BUTTON,EXIT_BTN
nodelist = SHIPS_SCROLL,LEFTSCROLLBUTTON,RIGHTSCROLLBUTTON

[FADER]
bAbsoluteRectangle = 15
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[DUST]
position 	= -200,-300,1000,1000
techniqueName	= iRotate
textureName	= interfaces\Recon\dust.tga
textureRect	= 0,0,1.0,1.0
color		= 200,200,200,200
rotate		= -0.03,0.005
speed		= 6000,0.0,0

[EXIT_BTN]
position = 675,83,695,103
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
command = deactivate,event:exitCancel
shadowColor = 0,0,0,0
bShowGlowCursor = 0
shadowoffset = -1,-1

[MAIN_FRAME]
command = activate
command = click,select:MAIN_FRAME
command = deactivate,event:ExitCancel
command = rightstep
command = leftstep
command = speedright
command = speedleft
position = 100,80,700,510
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(235,150,150,150)
rowquantity = 2
colquantity = 1
hlineheight = 1
headerlineheight = 1
cellspacesize = 2,1
fontcellscale = 0.8
colswidth = 348
rowsheight = 30,444
vlinewidth = 1
captionheight = 24
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captiondividerheight = 1
bShowGlowCursor=0

[TITLE_MAIN]
bAbsoluteRectangle = 5
position = 236,82,564,102
font = interface_button
fontScale = 1.1
lineSpace = 10
alignment = center
Color = 255,255,255,200
string = titleHireCrew

[MAIN_CHARACTER_PICTURE]
position = 135,115,190,170
textureName = interfaces\portraits\128\face_1.tga

[OTHER_PICTURE]
position = 610,115,665,170
textureName = interfaces\Tavern.tga
bShowGlowCursor = 0

[BORDER_PICTURE_1]
textureName = interfaces\emptyborder.tga
position = 135,115,190,170

[BORDER_PICTURE_2]
textureName = interfaces\emptyborder.tga
position = 610,115,665,170

[SHIPS_SCROLL]
command = activate
command = deactivate,event:ExitCancel
command = rightstep
command = leftstep
command = speedright
command = speedleft
command = click,select:SHIPS_SCROLL
position = 255,115,545,170
imageSize = 55,55
wDelta = 3
glowoffset = 0,0

[LEFTSCROLLBUTTON]
command = activate,select:SHIPS_SCROLL,com:speedleft:SHIPS_SCROLL
command = click,select:SHIPS_SCROLL,com:leftstep:SHIPS_SCROLL,com:activate:LEFTSCROLLBUTTON
position = 340,120,375,165
group = ICONS
picture = left arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[RIGHTSCROLLBUTTON]
command = activate,select:SHIPS_SCROLL,com:speedright:SHIPS_SCROLL
command = click,select:SHIPS_SCROLL,com:rightstep:SHIPS_SCROLL,com:activate:RIGHTSCROLLBUTTON
position = 425,120,460,165
group = ICONS
picture = right arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[INFO_SHIP]
position = 135,182,400,210
fontScale = 0.85
lineSpace = 14
alignment = left

[TAVERN_PRICE]
position = 400,182,665,210
fontScale = 0.85
lineSpace = 14
alignment = right

[OUR_GOLD]
position = 128,465,307,498
fontScale = 0.85
lineSpace = 15
alignment = center
Color = 255,255,255,156

[FOOD_SHIP]
position = 334,465,474,498
fontScale = 0.85
lineSpace = 15
alignment = center
Color = 255,255,255,255

[MONEY_SHIP]
position = 522,465,685,498
fontScale = 0.85
lineSpace = 15
alignment = center
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[CREW_PICTURE]
position = 125,210,200,285
textureName = interfaces\portraits\128\face_1.tga
bShowGlowCursor = 0

[CREW_QTY]
position = 113,290,214,315
lineSpace = 22
font = Bold_numbers
fontScale = 0.95

[CREW_MORALE_PIC]
position = 140,315,185,360
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[CREW_MORALE_TEXT]
position = 194,330,389,350
fontScale = 1.0
lineSpace = 16
alignment = left

[BAR_Sailors]
position = 280,246,380,249

[BAR_Cannoners]
position = 280,278,380,281

[BAR_Soldiers]
position = 280,310,380,313

[TABLE_CREW]
command = click,select:TABLE_CREW
command = rclick,select:TABLE_CREW,event:ShowInfoWindow
command = deactivate,event:exitCancel
command = upstep
command = downstep
command = leftstep
command = rightstep
command = speedleft
command = speedright
position = 198,220,389,320
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(0,128,128,128)
vlinewidth = 0
borderwidth = 0
hlineheight = 1
headerlineheight = 0
bordercornersize = 0,0
rowquantity = 4
colquantity = 4
fontcellvalignment = center
selectimage = color=(0,128,48,48)
colswidth = 30,56,97,4
rowsheight = 1,32,32,32
NormalLineHeight = 32
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[CREW_PICTURE2]
position = 401,210,476,285
textureName = interfaces\portraits\128\face_1.tga
bShowGlowCursor = 0

[CREW_QTY2]
position = 380,290,500,315
lineSpace = 22
font = Bold_numbers
fontScale = 0.95

[CREW_MORALE_PIC2]
position = 416,315,461,360
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[CREW_MORALE_TEXT2]
position = 470,330,665,350
fontScale = 1.0
lineSpace = 16
alignment = left

[BAR_Sailors2]
position = 566,246,665,249

[BAR_Cannoners2]
position = 566,278,665,281

[BAR_Soldiers2]
position = 566,310,665,313

[TABLE_CREW2]
command = click,select:TABLE_CREW2
command = rclick,select:TABLE_CREW2,event:ShowInfoWindow
command = deactivate,event:exitCancel
command = upstep
command = downstep
command = leftstep
command = rightstep
command = speedleft
command = speedright
position = 474,220,665,320
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(0,128,128,128)
vlinewidth = 0
borderwidth = 0
hlineheight = 1
headerlineheight = 0
bordercornersize = 0,0
rowquantity = 4
colquantity = 4
fontcellvalignment = center
selectimage = color=(0,128,48,48)
colswidth = 30,56,97,4
rowsheight = 1,32,32,32
NormalLineHeight = 32
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[V_QTY_EDIT]
bAbsoluteRectangle = 0
position = 366,381,443,406
sTexture = bigbutton
color = 120,60,80,70

[QTY_EDIT]
command = click,select:QTY_EDIT
command = deactivate,event:exitCancel
command = activate,event:confirmChangeQTY_EDIT
position = 374,381,437,406
strFont = interface_button
argbFontColor = 255,255,255,255
stringLength = 5
stringWidth = 80
stringalign = center
stringoffset = 9,3
MiddleImage = color=(0,128,128,128), piclist=MAIN_ICONS, picname=middle side button
excludechars = qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM ёйцукенгшщзхъфывапролджэячсмитьбю	ЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ!@#№$%^&*()_-+=~`'"|\/?:;<>,.{}[]

[QTY_ADD_ALL_BUTTON]
command = click,event:ADD_ALL_BUTTON,select:MAIN_FRAME
group = ARROWS
picture = left_all
position = 315,381,340,406
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_ADD_BUTTON]
command = click,event:ADD_BUTTON,select:MAIN_FRAME
group = ARROWS
picture = left
position = 343,381,368,406
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_REMOVE_BUTTON]
command = click,event:REMOVE_BUTTON,select:MAIN_FRAME
group = ARROWS
picture = right
position = 440,381,465,406
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_REMOVE_ALL_BUTTON]
command = click,event:REMOVE_ALL_BUTTON,select:MAIN_FRAME
command = activate
group = ARROWS
picture = right_all
position = 468,381,493,406
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_OK_BUTTON]
command = activate,event:TransactionOK
command = click,event:TransactionOK
command = deactivate,event:exitCancel
position = 250,425,390,457
string = Ok
fontScale = 1
glowoffset = 0,0
command = rightstep,com:click:QTY_REMOVE_BUTTON
command = leftstep,com:click:QTY_ADD_BUTTON
command = speedright,com:click:QTY_REMOVE_ALL_BUTTON
command = speedleft,com:click:QTY_ADD_ALL_BUTTON

[QTY_CANCEL_BUTTON]
command = activate,event:TransactionCancel
command = click,event:TransactionCancel
command = deactivate,event:exitCancel
position = 415,425,555,457
string = Cancel
fontScale = 1
glowoffset = 0,0
command = rightstep,com:click:QTY_REMOVE_BUTTON
command = leftstep,com:click:QTY_ADD_BUTTON
command = speedright,com:click:QTY_REMOVE_ALL_BUTTON
command = speedleft,com:click:QTY_ADD_ALL_BUTTON

[QTY_TypeOperation]
position = 240,361,573,385
fontScale = 1.2
lineSpace = 20
alignment = center
backoffset = 1,2,0,-2
Color = 255,255,255,156

[QTY_Result]
position = 240,408,573,429
fontScale = 0.9
lineSpace = 20
alignment = center
backoffset = 1,2,0,-2
Color = 255,255,255,156

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; SALARY_REQUIREMENT_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[SALARY_REQUIREMENT_WINDOW]
show = 0
nodelist = SALARY_REQUIREMENT_FADER,SALARY_REQUIREMENT_FRAME,SALARY_REQUIREMENT_CAPTION,SALARY_REQUIREMENT_WINDOW_TEXT,SALARY_REQUIREMENT_ACCEPT,SALARY_REQUIREMENT_CANCEL,SALARY_REQUIREMENT_EXIT

[SALARY_REQUIREMENT_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[SALARY_REQUIREMENT_FRAME]
position = 210,168,590,350
captionheight = 28
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captionoffset = 0,0,0,0
captiondividerheight = 1
backimage = piclist=RECON_ICONS, picname=confirm window caption, color=(255,150,150,150)
lefttop_size		= 12,12
righttop_size		= 12,12
leftbottom_size		= 12,12
rightbottom_size	= 12,12

[SALARY_REQUIREMENT_CAPTION]
command = click
bAbsoluteRectangle = 5
position = 247,172,555,224
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255, 255, 255, 255
backoffset = 1, 2, 0, -2

[SALARY_REQUIREMENT_WINDOW_TEXT]
command = click
position = 218,218,585,322
fontScale = 1.0
lineSpace = 20
alignment = center
Color = 255, 255, 255, 255

[SALARY_REQUIREMENT_ACCEPT]
bBreakCommand = 1
command = activate
command = click,event:AcceptSalaryRequirement
command = deactivate,event:ExitSalaryReqMenu
position = 248,308,398,340
string = AcceptPay
glowoffset = 0,0

[SALARY_REQUIREMENT_CANCEL]
bBreakCommand = 1
command = activate
command = click,event:DeclineSalaryRequirement
command = deactivate,event:ExitSalaryReqMenu
position = 402,308,552,340
string = Decline
glowoffset = 0,0

[SALARY_REQUIREMENT_EXIT]
position = 560,172,582,194
group = ICONS_SPEC
picture = exit button
command = click,event:ExitSalaryReqMenu
shadowColor = 0,0,0,0= 0,0,0,0