;Информационное сообщение

[MAIN]
item = 10,FRAME,MAIN_FRAME
item = 10,PICTURE,INFO_PICTURE
item = 10,SLIDEPICTURE,DUST
item = 35,FORMATEDTEXT,MAIN_CAPTION
item = 20,pc,BUTTON,EXIT_BTN
item = 50,FORMATEDTEXT,INFO_TEXT
item = 50,SCROLLER,INFO_SCROLL
start = INFO_TEXT

[MAIN_FRAME]
captionheight = 24
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captionoffset = 0,3,0,0
captiondividerheight = 4
position = 42,91,744,411

[INFO_PICTURE]
bAbsoluteRectangle = 5
position = 178,121,-24,185
textureName = interfaces\info.tga

[DUST]
position = 149,43,653,453
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[MAIN_CAPTION]
position = 49,93,737,111
font = INTERFACE_TITLE
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255,255,255,200

[EXIT_BTN]
position = 747,94,767,112
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
shadowColor = 0,0,0,0

[INFO_TEXT]
command = click,select:INFO_TEXT
command = activate,select:INFO_TEXT
command = deactivate,event:exitCancel
command = downstep
command = upstep
command = speeddown
command = speedup
position = 114,125,739,404
font = interface_normal
fontScale = 0.9
lineSpace = 16
alignment = left
Color = 255,255,255,255
bUseWheel = 1
scrollername = INFO_SCROLL
bShowGlowCursor = 0

[INFO_SCROLL]
command = activate
command = click
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 745,117,753,410
ownedcontrol = INFO_TEXT

