[COMMON]
RepeatDelay	= 250
mouseoutzonewidth = 5
mouseoutzoneheight = 5
mouseDblClickInterval = 600
; texture name, sensitive
MousePointer	= Interfaces\cursor32.tga,10,size:(32,32),pos:(-16,-16)
columnQuantity		= 15
waveAmplitude		= 0.1
wavePhase		= 0.4
waveSpeed		= 0.2
waveStepQuantity	= 300
blendSpeed		= 4
BlindTime	= 1.0

[PC_SCREEN_4:3]
fScale			= 1.0
wScreenWidth	= 1066
wScreenHeight	= 800
wScreenLeft		= 133
wScreenTop		= 100
wScreenRight	= 933
wScreenDown		= 700

[PC_SCREEN_5:4]
fScale			= 1.0
wScreenWidth	= 1066
wScreenHeight	= 854
wScreenLeft		= 133
wScreenTop		= 127
wScreenRight	= 933
wScreenDown		= 727

[PC_SCREEN_16:9]
fScale			= 1.0
wScreenWidth	= 1066
wScreenHeight	= 600
wScreenLeft		= 133
wScreenTop		= 0
wScreenRight	= 933
wScreenDown		= 600

[PC_SCREEN_16:10]
fScale			= 1.0
wScreenWidth	= 1066
wScreenHeight	= 666
wScreenLeft		= 133
wScreenTop		= 33
wScreenRight	= 933
wScreenDown		= 633

[PC_SCREEN_21:9]
fScale          = 1.0
wScreenWidth    = 1400
wScreenHeight   = 600
wScreenLeft     = 300
wScreenTop      = 0
wScreenRight    = 1100
wScreenDown     = 600

[PC_SCREEN_32:9]
fScale          = 1.0
wScreenWidth    = 2132
wScreenHeight   = 600
wScreenLeft     = 666
wScreenTop      = 0
wScreenRight    = 1466
wScreenDown     = 600

[PC_SCREEN_43:18]
fScale          = 1.0
wScreenWidth    = 1432
wScreenHeight   = 600
wScreenLeft     = 316
wScreenTop      = 0
wScreenRight    = 1116
wScreenDown     = 600

[PC_SCREEN]
fScale			= 1.0
wScreenWidth	= 1066
wScreenHeight	= 600
wScreenLeft		= 133
wScreenTop		= 0
wScreenRight	= 933
wScreenDown		= 600

; default settings
;bDynamicScaling = 1
;fScale          = 1.0
;wScreenWidth    = 800
;wScreenHeight   = 600
;wScreenLeft     = 0
;wScreenTop      = 0
;wScreenRight    = 800
;wScreenDown     = 600