;
; Recon интерфейс "Предметы"
;

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 10,SLIDEPICTURE,DUST
item = 20,VIDEORECTANGLE,V_ITEMS
item = EXIT,EB
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	TOP_MENU
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = PICTURE,TOP_LINE
item = PICTURE,TAB_MARK
item = PICTURE,TAB_GLOW
item = BUTTON,I_CHARACTER_2
item = BUTTON,I_SHIP_2
item = BUTTON,I_QUESTBOOK_2
item = BUTTON,I_ALCHEMY_2
item = BUTTON,I_ITEMS_2
item = BUTTON,I_NATIONS_2
item = STRINGCOLLECTION,STR_BUTTONS
item = STRINGCOLLECTION,STR_TITLE
item = 400,IMAGECOLLECTION,KEY_BTNS
item = 400,STRINGCOLLECTION,KEY_STRS
item = IMAGECOLLECTION,ADD_INFO
item = FORMATEDTEXT,WEIGHT
item = FORMATEDTEXT,MONEY
item = FORMATEDTEXT,CURRENT_DATE_CAPTION
item = ALERT,A_QUESTBOOK
item = ALERT,A_RECIPE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 120,PICTURE,TABBTN_1
item = 125,FORMATEDTEXT,TABSTR_1
item = 120,PICTURE,TABBTN_2
item = 125,FORMATEDTEXT,TABSTR_2
item = 120,PICTURE,TABBTN_3
item = 125,FORMATEDTEXT,TABSTR_3
item = 120,PICTURE,TABBTN_4
item = 125,FORMATEDTEXT,TABSTR_4
item = 120,PICTURE,TABBTN_5
item = 125,FORMATEDTEXT,TABSTR_5
item = 200,TABLE,TABLE_ITEMS
item = 201,SCROLLER,SCROLL_ITEMS
item = 400,TEXTBUTTON2,EQUIP_BUTTON
item = 200,FRAME,CHARACTERS_SCROLL_FRAME
item = 400,RECTANGLE,CHARACTERS_BACK
item = 400,RECTANGLE,CHARACTERS_BACK_HI
item = 400,VIMAGESCROLL,CHARACTERS_SCROLL
item = 400,BUTTON,UP_BUTTON
item = 400,BUTTON,DOWN_BUTTON
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 400,FRAME,SETUP_FRAME
item = 402,FORMATEDTEXT,SETUP_FRAME_CAPTION
item = 399,PICTURE,SETUP_BIG_PICTURE
item = 403,PICTURE,SLOT_BLADE
item = 403,PICTURE,SLOT_GUN
item = 403,PICTURE,SLOT_SPYGLASS
item = 403,PICTURE,SLOT_CUIRASS
item = 403,PICTURE,SLOT_MUSKET
item = 403,PICTURE,SLOT_AMMO_GUN
item = 403,PICTURE,SLOT_POWDER_GUN
item = 403,PICTURE,SLOT_AMMO_MUSKET
item = 403,PICTURE,SLOT_POWDER_MUSKET
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 300,FRAME,INFO_FRAME
;item = 200,VIDEO,VIDEO_INFO
item = 403,PICTURE,INFO_PIC
item = 555,FORMATEDTEXT,INFO_TEXT
item = 403,PICTURE,Weight_PIC
item = 555,FORMATEDTEXT,Weight_TEXT
item = 403,PICTURE,Money_PIC
item = 555,FORMATEDTEXT,Money_TEXT
item = WINDOW,MAIN_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 601,SLIDEPICTURE,MAP_DUST
item = 606,pc,BUTTON,MAP_EXIT_BTN
item = 600,RECTANGLE,MAP_FADER
item = 604,FRAME,MAP_FRAME
item = 605,FORMATEDTEXT,MAP_CAPTION
item = 610,PICTURE,MAP_PICTURE
item = 620,FORMATEDTEXT,MAP_TEXT
item = WINDOW,MAP_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 716,PICTURE,READ_PAPER
item = 720,FORMATEDTEXT,READ_TEXT
item = 730,QB_SCROLLER,READ_SCROLL
item = 736,pc,BUTTON,READ_EXIT_BTN
item = WINDOW,READ_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; MSG_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 753,RECTANGLE,MSG_FADER
item = 754,SLIDEPICTURE,MSG_DUST
item = 755,FRAME,MSG_WINDOW_FRAME
item = 755,FORMATEDTEXT,MSG_WINDOW_CAPTION
item = 755,FORMATEDTEXT,MSG_WINDOW_TEXT
item = 775,TEXTBUTTON2,MSG_OK
item = WINDOW,MSG_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
start = TABLE_ITEMS

[MAIN_WINDOW]
show = 1
nodelist = TABBTN_1,TABSTR_1,TABBTN_2,TABSTR_2,TABBTN_3,TABSTR_3,TABBTN_4,TABSTR_4,,TABBTN_5,TABSTR_5
nodelist = CHARACTERS_SCROLL_FRAME,UP_BUTTON,DOWN_BUTTON,EQUIP_BUTTON,SCROLL_ITEMS,TABLE_ITEMS

[MAIN_BACK]
bAbsoluteRectangle = 0
;position = -134,0,933,600
position = -169,-269,969,869
textureName = interfaces\Recon\bgr_interface.tga

[EB]
command = click,event:exitCancel

; анимация (крутится)
[DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[V_ITEMS]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[A_QUESTBOOK]
position = 360,1,374,15

[A_RECIPE]
position = 457,1,471,15

[TOP_LINE]
position = -133,44,933,45
groupName = le_icons
picName = border_hs

[TAB_MARK]
position = 346,43,416,46
groupName = tabs2
picName = TabSelectedMark

[TAB_GLOW]
position = 326,0,437,44
groupName = tabs2
picName = TabSelected
blind = 1
blindUpTime = 2.0
blindDownTime = 2.0
blindMinColor = 50,128,128,128
blindMaxColor = 225,128,128,128

[STR_BUTTONS]
string = buttonCharacter,font:interface_normal,pos:{195,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonShip,font:interface_normal,pos:{282,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonAlchemy,font:interface_normal,pos:{458,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonQuestBook,font:interface_normal,pos:{365,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonNation,font:interface_normal,pos:{624,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}

[STR_TITLE]
string = Sel Items,font:interface_normal,pos:{542,16},fc:{255,255,255,255},bc:{0,128,128,128},scale:1.11,state:{CS}

[KEY_BTNS]
groupName = keyboard_icons
picture = q,col:{255,75,75,75},pos:{91,11,119,38}
picture = e,col:{255,75,75,75},pos:{680,11,708,38}
picture = rmb,col:{255,128,128,128},pos:{537,561,565,588}
picture = esc,col:{255,128,128,128},pos:{680,561,708,588}

[KEY_STRS]
string = help,font:interface_normal,pos:{577,566},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{L}
string = back,font:interface_normal,pos:{724,566},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{L}

[ADD_INFO]
groupName = icons_char
picture = weight,col:{255,128,128,128},pos:{-117,16,-97,36}
picture = money,col:{255,128,128,128},pos:{-31,16,-11,36}

[WEIGHT]
command = click
command = rclick,select:WEIGHT,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = -89,19,-29,36
fontScale = 0.78
lineSpace = 10
alignment = left
bShowGlowCursor = 0

[MONEY]
command = click
command = rclick,select:MONEY,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = -9,19,77,36
fontScale = 0.78
lineSpace = 10
alignment = left
bShowGlowCursor = 0

[CURRENT_DATE_CAPTION]
command = click
position = 707,16,932,38
fontScale = 1.11
lineSpace = 10
alignment = center
string = Current Date and time

[I_CHARACTER_2]
bBreakCommand = 1
command = click
position = 136,0,253,44

[I_SHIP_2]
bBreakCommand = 1
command = click
position = 253,0,341,44

[I_QUESTBOOK_2]
bBreakCommand = 1
command = click
position = 341,0,427,44

[I_ALCHEMY_2]
bBreakCommand = 1
command = click
position = 427,0,499,44

[I_ITEMS_2]
bBreakCommand = 1
command = click
position = 499,0,585,44

[I_NATIONS_2]
bBreakCommand = 1
command = click
position = 585,0,663,44

[CHARACTERS_SCROLL_FRAME]
position = 10,65,160,550
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(225,128,128,128)

[CHARACTERS_BACK]
position = 17,276,159,339
leftColor = 150,200,200,200
topColor = 150,200,200,200
rightColor = 120,41,17,0
bottomColor = 120,41,17,0
borderColor = 255,106,76,57

[CHARACTERS_BACK_HI]
position = 17,276,159,339
leftColor = 150,200,200,200
topColor = 150,200,200,200
rightColor = 50,200,200,2000
bottomColor = 150,200,200,200
borderColor = 255,0,0,0

[UP_BUTTON]
command = click,select:CHARACTERS_SCROLL,com:upstep:CHARACTERS_SCROLL,com:activate:UP_BUTTON
position = 17,70,80,80
group = SCROLL_ARROWS
picture = scrollArrowUp
shadowOffset = 0,0

[DOWN_BUTTON]
command = click,select:CHARACTERS_SCROLL,com:downstep:CHARACTERS_SCROLL,com:activate:DOWN_BUTTON
position = 17,535,80,545
group = SCROLL_ARROWS
picture = scrollArrowDown
shadowOffset = 0,0

[CHARACTERS_SCROLL]
bUseWheel = 1
command = rclick,select:CHARACTERS_SCROLL,event:ShowInfoWindow
command = click,select:CHARACTERS_SCROLL
command = upstep
command = downstep
command = deactivate,event:exitCancel
command = activate,select:CHARACTERS_SCROLL,event:OfficerChange
imageSize = 63,63
wDelta = 1
position = 17,83,80,532
glowoffset = 0,0
centerYoffset = 225
stringsquantity = 5
dwXOffset1 = 36
dwYOffset1 = -30
scale1 = 0.8
align1 = left
font1 = interface_normal
dwForeColor1 = 255,255,255,200
dwBackColor1 = 0,0,0,0
dwXOffset2 = 36
dwYOffset2 = 0
scale2 = 0.74
align2 = left
font2 = interface_normal
dwForeColor2 = 255,255,255,255
dwBackColor2 = 0,0,0,0
dwXOffset3 = 36
dwYOffset3 = 16
scale3 = 0.74
align3 = left
font3 = interface_normal
dwForeColor3 = 255,255,255,255
dwBackColor3 = 0,0,0,0
dwXOffset4 = 36
dwYOffset4 = -15
scale4 = 0.7
align4 = left
font4 = interface_normal
dwForeColor4 = 255,200,200,200
dwBackColor4 = 0,0,0,0
dwXOffset5 = 28
dwYOffset5 = 6
scale5 = 0.7
align5 = right
font5 = Bold_numbers
dwForeColor5 = 255,255,255,255
dwBackColor5 = 0,0,0,0
leftTextLimit = 0
rightTextLimit = 100

[SETUP_FRAME]
captionheight = 25
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(0,128,128,128)
captionoffset = 0,0,0,0
captiondividerheight = 1
position = 500,65,790,425
topline_height = 1
bottomline_height = 1
leftline_width = 1
rightline_width = 1

[SETUP_FRAME_CAPTION]
command = click
position = 500,68,790,78
font = interface_button
fontScale = 1.0
lineSpace = 10

[SETUP_BIG_PICTURE]
position = 500,88,790,425
;textureName = interfaces\Recon\CharacterEquipment_SLIB.tga
bShowGlowCursor = 0

[VIDEO_INFO]
bAbsoluteRectangle = 0
position = 165,430,790,550
color = 150,128,128,128

[INFO_FRAME]
position = 165,430,790,550
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(205,128,128,128)

[TABBTN_1]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = rclick,select:TABBTN_1,event:ShowInfoWindow
position = 165,65,220,91
groupName = TABS
picName = TabDeSelected
bShowGlowCursor = 0

[TABSTR_1]
position = 165,65,220,91
fontscale = 0.8
lineSpace = 12
valignment = 1
string = All

[TABBTN_2]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = rclick,select:TABBTN_2,event:ShowInfoWindow
position = 225,65,300,91
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_2]
position = 225,65,300,91
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Item_WEAPON

[TABBTN_3]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = rclick,select:TABBTN_3,event:ShowInfoWindow
position = 305,65,365,91
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_3]
position = 305,65,365,91
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Item_POTIONS

[TABBTN_4]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = rclick,select:TABBTN_4,event:ShowInfoWindow
position = 370,65,430,91
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_4]
position = 370,65,430,91
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Item_QUESTITEMS

[TABBTN_5]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
command = rclick,select:TABBTN_5,event:ShowInfoWindow
position = 435,65,495,91
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_5]
position = 435,65,495,91
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Item_VARIETY

[TABLE_ITEMS]
command = click,select:TABLE_ITEMS
command = rclick,select:TABLE_ITEMS,event:ShowInfoWindow
command = dblclick,select:TABLE_ITEMS,event:ChooseItem
command = deactivate,event:exitCancel
command = upstep
command = downstep
position = 165,90,415,284
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(235,140,140,140)
scroller = SCROLL_ITEMS
borderwidth = 1
vlinewidth = 1
hlineheight = 1
headerlineheight = 1
bordercornersize = 10,10
rowquantity = 10
colquantity = 4
fontcellvalignment = center
colswidth = 184,45,45,45
rowsheight = 28,34,34,34,34,34,34,34,34,34
NormalLineHeight = 32

[SCROLL_ITEMS]
command = click, select:TABLE_ITEMS
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 485,90,495,425
ownedcontrol = TABLE_ITEMS

[SLOT_BLADE]
position = 696,213,765,282
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0
command = click,event:ClickToBlade,select:SLOT_BLADE
command = deactivate,event:exitCancel

[SLOT_GUN]
position = 525,213,594,282
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0
command = click,event:ClickToGun,select:SLOT_GUN
command = deactivate,event:exitCancel

[SLOT_SPYGLASS]
position = 525,317,594,386
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0
command = click,event:ClickToSpyGlass,select:SLOT_SPYGLASS
command = deactivate,event:exitCancel

[SLOT_CUIRASS]
position = 611,213,680,282
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0
command = click,event:ClickToCirass,select:SLOT_CUIRASS
command = deactivate,event:exitCancel

[SLOT_MUSKET]
position = 696,109,765,178
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0
command = click,event:ClickToMusket,select:SLOT_MUSKET
command = deactivate,event:exitCancel

[INFO_PIC]
position = 300,440,400,540
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[INFO_TEXT]
position = 405,435,785,545
fontScale = 0.77
lineSpace = 13
alignment = center

[Money_PIC]
position = 175,478,200,503
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[Money_TEXT]
position = 205,485,295,500
fontScale = 0.81
lineSpace = 15
alignment = right
color = 255,255,228,80

[Weight_PIC]
position = 175,513,200,538
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[Weight_TEXT]
position = 205,519,295,534
fontScale = 0.80
lineSpace = 15
alignment = right

[EQUIP_BUTTON]
command = activate
command = click
command = deactivate,event:exitCancel
position = 175,440,295,468
string = Equip that
fontScale = 0.9
glowoffset = 0,0

[SLOT_AMMO_GUN]
position = 538,286,557,305
textureName = alpha_path.tga
bShowGlowCursor = 0
;color = 255,128,128,128
blind = 0
blindUpTime = 1.5
blindDownTime = 1.0
blindMinColor = 255,128,64,64
blindMaxColor = 255,192,128,128
command = click,event:ClickToAmmo,select:SLOT_AMMO_GUN
command = deactivate,event:exitCancel

[SLOT_POWDER_GUN]
position = 562,286,581,305
textureName = alpha_path.tga
bShowGlowCursor = 0
;color = 255,128,128,128
blind = 0
blindUpTime = 1.5
blindDownTime = 1.0
blindMinColor = 255,128,64,64
blindMaxColor = 255,192,128,128
command = click,event:ClickToAmmo,select:SLOT_POWDER_GUN
command = deactivate,event:exitCancel

[SLOT_AMMO_MUSKET]
position = 709,183,728,202
textureName = alpha_path.tga
bShowGlowCursor = 0
;color = 255,128,128,128
blind = 0
blindUpTime = 1.5
blindDownTime = 1.0
blindMinColor = 255,128,64,64
blindMaxColor = 255,192,128,128
command = click,event:ClickToAmmo,select:SLOT_AMMO_MUSKET
command = deactivate,event:exitCancel

[SLOT_POWDER_MUSKET]
position = 733,183,752,202
textureName = alpha_path.tga
bShowGlowCursor = 0
;color = 255,128,128,128
blind = 0
blindUpTime = 1.5
blindDownTime = 1.0
blindMinColor = 255,128,64,64
blindMaxColor = 255,192,128,128
command = click,event:ClickToAmmo,select:SLOT_POWDER_MUSKET
command = deactivate,event:exitCancel
;;;;;;;;;;;;;;;

[MAP_WINDOW]
show = 0
nodelist = MAP_FRAME,MAP_EXIT_BTN,MAP_FADER,MAP_CAPTION,MAP_TEXT,MAP_PICTURE,MAP_DUST

[MAP_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[MAP_DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 220,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[MAP_FRAME]
position = 50,20,750,580
captionheight = 28
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captionoffset = 0,0,0,0
captiondividerheight = 2
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(255,128,128,128)

[MAP_CAPTION]
bAbsoluteRectangle = 5
position = 245,25,578,55
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
backoffset = 1,2,0,-2
string = titleMapRead

[MAP_EXIT_BTN]
position = 721,25,743,47
group = ICONS_SPEC
picture = exit button
command = click,event:ExitMapWindow
shadowColor = 0,0,0,0
bShowGlowCursor = 0
glowoffset = 0,0

[MAP_TEXT]
command = click
command = deactivate,event:ExitMapWindow
position = 190,96,622,504
fontScale = 1.5
lineSpace = 30
alignment = center
font = interface_button
bShowGlowCursor = 0

[MAP_PICTURE]
position = 50,50,750,580
;textureName = interfaces\CharacterEquipment_SLIB.tga
bShowGlowCursor = 0
;;;;;;;;;;;;;;;

[READ_WINDOW]
show = 0
nodelist = READ_EXIT_BTN,READ_TEXT,READ_SCROLL,READ_PAPER

[READ_PAPER]
bAbsoluteRectangle = 0
position = 10,65,790,558
textureName = interfaces\Recon\papirus_read.tga
color = 250,128,128,128

[READ_EXIT_BTN]
position = 765,70,785,88
group = ICONS_SPEC
picture = exit button
command = click,event:ExitReadWindow
shadowColor = 0,0,0,0
bShowGlowCursor = 0
glowoffset = 0,0

[READ_TEXT]
bAbsoluteRectangle = 0
command = click
command = deactivate,event:ExitReadWindow
command = downstep
command = upstep
command = speeddown
command = speedup
position = 63,155,737,503
lineSpace = 25
alignment = left
font = interface_quest_text
scrollername = READ_SCROLL
bShowGlowCursor = 0

[READ_SCROLL]
command = activate
command = deactivate,event:ExitReadWindow
command = downstep
command = upstep
command = click
position = 745,137,759,499
ownedcontrol = READ_TEXT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; MSG_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[MSG_WINDOW]
show = 0
nodelist = MSG_FADER,MSG_DUST,MSG_OK,MSG_WINDOW_FRAME,MSG_WINDOW_CAPTION,MSG_WINDOW_TEXT

[MSG_WINDOW_CAPTION]
position = 180,218,620,240
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
string = HideWeaponTitle

[MSG_WINDOW_TEXT]
command = click
position = 190,260,610,380
fontScale = 1.0
lineSpace = 20
alignment = center
Color = 255,255,255,255
string = HideWeaponText

[MSG_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[MSG_DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[MSG_OK]
bBreakCommand = 1
command = click,event:ExitMsgMenu
command = activate,event:ExitMsgMenu
command = deactivate,event:ExitMsgMenu
position = 320,325,480,355
string = Ok
glowoffset = 0,0

[MSG_WINDOW_FRAME]
captionheight = 25
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = 180,215,620,360

