
[MAIN]
item = FRAME,MAIN_FRAME
;item = RECTANGLE,RECTANGLE_MIDDLE
;item = PICTURE,INFO_PICTURE
item = 110,FORMATEDTEXT,INFO_TEXT
item = 110,FORMATEDTEXT,INFO_TEXT_QUESTION
item = 100,TEXTBUTTON2,B_OK
item = 100,TEXTBUTTON2,B_CANCEL
item = 100,FORMATEDTEXT,MAP_CAPTION
item = 110, IMAGECOLLECTION,BORDERS
item = 90,FRAME,FRAME2
start = B_CANCEL

[MAIN_FRAME]
captionheight = 30
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(255,150,150,150)
captiondividerheight = 4
position = 225,220,575,395

[FRAME2]
position = 225,250,575,395
backimage = piclist=RECON_ICONS, picname=confirm window, color=(255,150,150,150)
lefttop_size = 0,0
righttop_size = 0,0
leftbottom_size = 10,10
rightbottom_size = 10,10

[BORDERS]
groupName = RECON_ICONS
picture = border topleft,col:{255,128,128,128},pos:{225,220,235,230}
picture = border topright,col:{255,128,128,128},pos:{565,220,575,230}
;picture = border bottomleft,col:{255,128,128,128},pos:{225,362,235,372}
;picture = border bottomright,col:{255,128,128,128},pos:{564,362,574,372}

[INFO_PICTURE]
position = 226,152,573,372
textureName = loading\flplndra.tga

[RECTANGLE_MIDDLE]
position = 225,372,574,373
leftColor = 120,41,17,0
topColor = 120,41,17,0
rightColor = 120,41,17,0
bottomColor = 120,41,17,0
borderColor = 255,106,76,57
glowoffset = 0,0

[B_OK]
bBreakCommand
command = deactivate,event:exitCancel
command = activate
command = click
command = rightstep,select:B_CANCEL
position = 255,357,397,386
string = LeaveBattle_yes
glowoffset = 0,0

[B_CANCEL]
bBreakCommand
command = deactivate,event:exitCancel
command = activate
command = click
command = leftstep,select:B_OK
position = 403,357,545,386
string = LeaveBattle_no
glowoffset = 0,0

[INFO_TEXT]
position = 233,260,570,347
fontScale = 0.9
lineSpace = 16
Color = 255,255,255,255
backoffset = 1,0,0,-2
glowoffset = 0,0

[INFO_TEXT_QUESTION]
position = 230,260,570,350
fontScale = 0.9
lineSpace = 10

[MAP_CAPTION]
bAbsoluteRectangle = 5
position = 251,123,548,149
fontScale = 1.1
lineSpace = 18
font = interface_button
alignment = center
Color = 255,255,255,255
backoffset = 1,0,0,-2
glowoffset = 0,0

