; Hokkins: обновленная верстка главного меню (27.06.2023)

[MAIN]
item = PICTURE,LOGO
item = PICTURE,POINTER
item = FORMATEDTEXT,SUBSCRIBE
item = FORMATEDTEXT,VERSION
item = TEXTBUTTON2,BTN_RESUMEGAME
item = TEXTBUTTON2,BTN_NEWGAME
item = TEXTBUTTON2,BTN_LOAD
item = TEXTBUTTON2,BTN_OPTIONS
item = TEXTBUTTON2,BTN_CREDITS
item = TEXTBUTTON2,BTN_QUIT
item = SMALLBUTTON,BTN_STEAM_URL
item = SMALLBUTTON,BTN_DISCORD
item = SMALLBUTTON,BTN_VK
item = PICTURE,ENGLISH_POINTER
item = SMALLBUTTON,ENGLISH_BTN_DISCORD
item = FORMATEDTEXT,NEW_GAME_INFO
; CHANGES WINDOW
item = 100,FRAME,CHANGES_FRAME_WINDOW
item = 110,FORMATEDTEXT,CHANGES_CAPTION
item = 110,BUTTON,CHANGES_BTN_EXIT
item = 110,FRAME,CHANGES_FRAME
item = 110,FORMATEDTEXT,CHANGES_TEXT
item = 110,SCROLLER,CHANGES_SCROLL
item = WINDOW,CHANGES_WINDOW
; QR CODE WINDOW
item = 100,PICTURE,QR_ZONE
item = 110,PICTURE,QR_DISCORD
item = 110,PICTURE,QR_VK
item = WINDOW,QR_WINDOW

[LOGO]
position = -70,43,260,179
groupName = MENU_BUTTONS
picName = Logo

[POINTER]
position = 622,20,645,55
groupName = MENU_BUTTONS
picName = Pointer

[ENGLISH_POINTER]
position = 622,20,645,55
groupName = ENGLISH_MENU_BUTTONS
picName = Pointer

[SUBSCRIBE]
position = 643,43,740,53
font = INTERFACE_NORMAL
fontScale = 0.65
lineSpace = 10
alignment = center
Color = 255,255,255,255

[VERSION]
position = 360,580,790,590
font = INTERFACE_NORMAL
fontScale = 0.8
lineSpace = 10
alignment = right
Color = 255,255,255,255

[BTN_NEWGAME]
command = click,event:NewGamePress
command = activate,event:NewGamePress
command = deactivate,event:HideChangesWindow
command = upstep,select:BTN_QUIT
command = downstep,select:BTN_RESUMEGAME
command = leftstep,select:BTN_VK
command = rightstep,select:BTN_DISCORD
position = -28,184,212,213
string = New Game
glowoffset = 0,0

[BTN_RESUMEGAME]
command = click,event:LoadLastSave
command = activate,event:LoadLastSave
command = deactivate,event:HideChangesWindow
command = upstep,select:BTN_NEWGAME
command = downstep,select:BTN_LOAD
command = leftstep,select:BTN_VK
command = rightstep,select:BTN_DISCORD
position = -28,216,212,245
string = Resume Game
glowoffset = 0,0

[NEW_GAME_INFO]
position = -28,193,212,222
font = interface_button
fontScale = 0.9
lineSpace = 15
alignment = center
color = 155,255,128,128
string = New Game Restart

[BTN_LOAD]
command = click,event:LoadPress
command = activate,event:LoadPress
command = deactivate,event:HideChangesWindow
command = upstep,select:BTN_NEWGAME
command = downstep,select:BTN_OPTIONS
command = leftstep,select:BTN_VK
command = rightstep,select:BTN_DISCORD
position = -28,248,212,277
string = Load
glowoffset = 0,0

[BTN_OPTIONS]
command = click,event:OptionsPress
command = activate,event:OptionsPress
command = deactivate,event:HideChangesWindow
command = upstep,select:BTN_LOAD
command = downstep,select:BTN_CREDITS
command = leftstep,select:BTN_VK
command = rightstep,select:BTN_DISCORD
position = -28,280,212,309
string = Options
glowoffset = 0,0

[BTN_CREDITS]
command = click,event:CreditsPress
command = activate,event:CreditsPress
command = deactivate,event:HideChangesWindow
command = upstep,select:BTN_OPTIONS
command = downstep,select:BTN_QUIT
command = leftstep,select:BTN_VK
command = rightstep,select:BTN_DISCORD
position = -28,312,212,341
string = Credits
glowoffset = 0,0

[BTN_QUIT]
command = click,event:QuitPress
command = activate,event:QuitPress
command = deactivate,event:HideChangesWindow
command = upstep,select:BTN_CREDITS
command = downstep,select:BTN_NEWGAME
command = leftstep,select:BTN_VK
command = rightstep,select:BTN_DISCORD
position = -28,344,212,373
string = Quit
glowoffset = 0,0

[BTN_STEAM_URL]
command = click,event:ShowPreorderURL
command = rclick,event:ShowPreorderURL
command = activate,event:ShowPreorderURL
command = deactivate,event:ShowPreorderURL
command = leftstep,select:BTN_NEWGAME
command = rightstep,select:BTN_DISCORD
position = 10,400,168,447
group = MENU_BUTTONS
buttonMiddle = Steam_Wishlist_unselect
selectButtonMiddle = Steam_Wishlist_select

[BTN_DISCORD]
command = click,event:ShowDiscordQRCodeWindow
command = rclick,event:ShowDiscordQRCodeWindow
command = activate,event:ShowDiscordQRCodeWindow
command = deactivate,event:HideQRCodeWindow
command = leftstep,select:BTN_NEWGAME
command = rightstep,select:BTN_VK
position = 640,0,670,30
group = MENU_BUTTONS
buttonMiddle = Discord_unselect
selectButtonMiddle = Discord_select

[ENGLISH_BTN_DISCORD]
command = click,event:ShowDiscordQRCodeWindow
command = rclick,event:ShowDiscordQRCodeWindow
command = activate,event:ShowDiscordQRCodeWindow
command = deactivate,event:HideQRCodeWindow
command = leftstep,select:ENGLISH_BTN_NEWGAME
command = rightstep,select:ENGLISH_BTN_NEWGAME
position = 640,0,670,30
group = ENGLISH_MENU_BUTTONS
buttonMiddle = Discord_unselect
selectButtonMiddle = Discord_select

[BTN_VK]
command = click,event:ShowVKQRCodeWindow
command = rclick,event:ShowVKQRCodeWindow
command = activate,event:ShowVKQRCodeWindow
command = deactivate,event:HideQRCodeWindow
command = leftstep,select:BTN_DISCORD
command = rightstep,select:BTN_NEWGAME
position = 670,0,700,30
group = MENU_BUTTONS
buttonMiddle = VK_unselect
selectButtonMiddle = VK_select

[CHANGES_WINDOW]
show = 0
nodelist = CHANGES_FRAME_WINDOW,CHANGES_CAPTION,CHANGES_BTN_EXIT
nodelist = CHANGES_FRAME,CHANGES_TEXT,CHANGES_SCROLL

[CHANGES_FRAME_WINDOW]
captionheight = 24
captionimage = piclist=SKILLS, picname=SKILLBORDER, color=(255,128,128,128)
captionoffset = 0,3,0,0
captiondividerheight = 4
position = 960,63,1390,560

[CHANGES_CAPTION]
position = 960,67,1390,87
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255,255,255,200

[CHANGES_BTN_EXIT]
position = 1360,67,1380,87
group = ICONS_SPEC
picture = exit button
command = click,event:HideChangesWindow
command = deactivate,event:HideChangesWindow
shadowColor = 0,0,0,0
bShowGlowCursor = 0
shadowoffset = -1,-1

[CHANGES_FRAME]
position = 970,98,1372,550

[CHANGES_TEXT]
command = click,select:CHANGES_TEXT
command = activate,select:CHANGES_TEXT
command = deactivate,event:HideChangesWindow
command = downstep
command = upstep
command = speeddown
command = speedup
position = 980,108,1362,550
alignment = left
font = interface_normal
fontScale = 0.79
Color = 255,255,255,255
lineSpace = 20
bUseWheel = 1
scrollername = CHANGES_SCROLL
bShowGlowCursor = 0

[CHANGES_SCROLL]
command = click, select:TABLE_LIST
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 1372,98,1380,550
baseTexture = interfaces\icons.tga
rollerTexture = interfaces\icons.tga
scrollTexPos = 0,0.75,0.045,1.0
rollTexPos = 0.0625,0.875,0.1075,0.96
begEndTexSize = 0.0835
begEndBaseSize = 18
rollerHeight = 18
ownedcontrol = CHANGES_TEXT

[QR_WINDOW]
show = 0
nodelist = QR_ZONE,QR_DISCORD,QR_VK

[QR_ZONE]
position = 643,58,740,155
groupName = MENU_BUTTONS
picName = QRZone

[QR_DISCORD]
command = click,event:HideQRCodeWindow
command = rclick,event:HideQRCodeWindow
command = activate,event:HideQRCodeWindow
command = deactivate,event:HideQRCodeWindow
position = 643,58,740,155
groupName = MENU_BUTTONS
picName = QR_Discord

[QR_VK]
command = click,event:HideQRCodeWindow
command = rclick,event:HideQRCodeWindow
command = activate,event:HideQRCodeWindow
command = deactivate,event:HideQRCodeWindow
position = 643,58,740,155
groupName = MENU_BUTTONS
picName = QR_VK

