; espkk # ActiveMap 1.2 # 30/Mar/2017 <--
; Hokkins: интерфейс отличной карты. Обновленная верстка (28.07.2022)

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 15,VIDEORECTANGLE,V_MAPVIEW
item = 20,SLIDEPICTURE,SLIDE_TITLE
item = 25,PICTURE,TITLE_HULL
item = 30,PICTURE,TITLE_RUSLEN
item = 35,TITLE,TITLE
item = 35,BUTTON,EXIT_BTN
;
item = 55,FRAME,MAP_BORDER
item = 50,PICTURE,MAP_PICTURE
item = 50,SCROLLEDPICTURE,MAP_ICONS
item = 55,PICTURE,BOUNDARIES
item = WINDOW,MAIN_WINDOW
;
; INFO_WINDOW
item = 100,RECTANGLE,INFO_FADER
item = 150,FRAME,INFO_FRAME
item = 150,FORMATEDTEXT,INFO_CAPTION
item = 155,FRAME,INFO_GOVERNOR_BORDER
item = 150,PICTURE,INFO_GOVERNOR_PORTRAIT
item = 150,TABLE,INFO_COLONY_TABLE
item = 150,PICTURE,INFO_NATION_PICTURE
item = 155,FORMATEDTEXT,COLONY_INFO_SIEGE
item = 155,FORMATEDTEXT,COLONY_TRAVEL_INFO
item = 150,TABLE,INFO_GOODS_TABLE
item = WINDOW,INFO_WINDOW

[MAIN_WINDOW]
show = 1
nodelist = TITLE,EXIT_BTN
nodelist = MAP_PICTURE,MAP_ICONS,BOUNDARIES

[MAIN_BACK]
bAbsoluteRectangle = 0
;position = -134,0,933,600
position = -169,-269,969,869
textureName = interfaces\Recon\bgr_black.tga

[V_MAPVIEW]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[SLIDE_TITLE]
position = 0,-35,800,70

[TITLE_HULL]
bAbsoluteRectangle = 0
position = -134,-31,933,570
textureName = interfaces\Recon\title_hull.tga

[TITLE_RUSLEN]
bAbsoluteRectangle = 0
position = 290,30,510,70
textureName = interfaces\Recon\title_ruslen.tga

[TITLE]
stringOffset = 15
stringWidth = 210

[EXIT_BTN]
position = 775,16,797,38
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
shadowColor = 0,0,0,0

[MAP_BORDER]
position = 10,80,790,590
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(0,128,128,128)
color = 255,128,128,128

[MAP_PICTURE]
position = 10,80,790,590
textureName = interfaces\maps\map_good.tga
color = 200,150,150,150

[MAP_ICONS]
command = click
command = rclick,event:SelectRColony
position = 120,100,690,580
basesize = 2048,2048

[BOUNDARIES]
position = 0,35,800,595

[INFO_WINDOW]
show = 0
nodelist = INFO_FADER,INFO_FRAME,INFO_CAPTION
nodelist = INFO_GOVERNOR_BORDER,INFO_GOVERNOR_PORTRAIT,INFO_NATION_PICTURE,INFO_COLONY_TABLE
nodelist = COLONY_TRAVEL_INFO,COLONY_INFO_SIEGE,INFO_GOODS_TABLE

[INFO_FADER]
bAbsoluteRectangle = 5
position = 0,0,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[INFO_FRAME]
captionheight = 24
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = 200,90,600,515

[INFO_CAPTION]
position = 200,94,600,114
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255,255,255,200

[INFO_GOVERNOR_BORDER]
position = 210,124,330,248
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(0,128,128,128)
color = 255,128,128,128

[INFO_GOVERNOR_PORTRAIT]
position = 210,124,330,248

[INFO_COLONY_TABLE]
command = deactivate,event:exitCancel
position = 335,124,590,244
vlinewidth = 0
hlineheight = 1
rowquantity = 6
colquantity = 2
fontcellvalignment = center
fontcellscale = 0.9
selectimage = color=(0,0,0,0)
colswidth = 125,125
rowsheight = 0,25,24,25,24,25
NormalLineHeight = 24

[INFO_NATION_PICTURE]
position = 216,131,246,161

[COLONY_TRAVEL_INFO]
position = 215,258,585,273
fontScale = 0.8
lineSpace = 15
alignment = left
Color = 255,255,255,255

[COLONY_INFO_SIEGE]
position = 215,258,585,273
fontScale = 0.8
lineSpace = 15
alignment = right
Color = 255,255,110,110

[INFO_GOODS_TABLE]
command = deactivate,event:exitCancel
position = 210,279,590,500
vlinewidth = 2
hlineheight = 2
rowquantity = 8
colquantity = 3
fontcellvalignment = center
fontcellscale = 0.9
selectimage = color=(0,0,0,0)
colswidth = 125,125,125
rowsheight = 24,28,28,28,28,28,28,28
NormalLineHeight = 28