; ReCon - Интерфейс "Атласа карт".

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 15,VIDEORECTANGLE,V_MAPVIEW
item = 10,SLIDEPICTURE,DUST
item = 35,TITLE,TITLE
item = 35,BUTTON,EXIT_BTN
item = 100,IMAGECOLLECTION,BORDERS
item = 55,PICTURE,MAPS_PICTURE
item = 50,TABLE,TABLE_MAPS
item = 55,SCROLLER,SCROLL_MAPS
item = 55,FORMATEDTEXT,STR_1
item = WINDOW,MAIN_WINDOW
start = TABLE_MAPS

[MAIN_WINDOW]
show = 1
nodelist = MAIN_BACK,TITLE,MAP,SCROLL_MAPS,TABLE_MAPS
nodelist = MAP_BORDER,EXIT_BTN

[MAIN_BACK]
bAbsoluteRectangle = 0
;position = -134,0,933,600
position = -169,-269,969,869
textureName = interfaces\Recon\bgr_interface.tga

[TITLE]
position = 0,25,800,60
stringOffset = 6
stringWidth = 220

[DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[V_MAPVIEW]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[BORDERS]
groupName = RECON_ICONS
; TABLE_MAPS
picture = border topleft,col:{255,128,128,128},pos:{615,60,625,70}
picture = border topright,col:{255,128,128,128},pos:{770,60,780,70}

[MAPS_FRAME]
position = 10,60,610,570
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(205,150,150,150)

[MAPS_PICTURE]
position = 7,60,607,570
textureName = interfaces\maps\kayman.tga

[TABLE_MAPS]
command = deactivate,event:exitCancel
command = click,select:TABLE_MAPS
command = rclick,select:TABLE_ITEMS,event:ShowInfoWindow
command = upstep
command = downstep
fontcellcolor = 255,255,255,255
fontcellalignment = center
fontcellvalignment = center
position = 615,60,780,570
backimage = piclist=RECON_TABLE, picname=bottom shadow, color=(255,128,128,128)
scroller = SCROLL_MAPS
vlinewidth = 2
hlineheight = 1
borderwidth = 1
rowquantity = 19
colquantity = 1
colswidth = 164
rowsheight = 25,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,26,26
NormalLineHeight = 27

[SCROLL_MAPS]
command = click, select:TABLE_MAPS
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 780,60,790,570
ownedcontrol = TABLE_MAPS

[STR_1]
position = 615,63,780,85
lineSpace = 19
font = INTERFACE_TITLE
fontScale = 0.85

[EXIT_BTN]
position = 770,34,790,52
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
shadowColor = 0,0,0,0

