;
; Recon Интерфейс "Нации"
;

[MAIN]
; задний фон
item = 10,PICTURE,MAIN_BACK
item = 10,SLIDEPICTURE,DUST
item = 20,VIDEORECTANGLE,V_NATION
item = EXIT,EB

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	TOP_MENU
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = PICTURE,TOP_LINE
item = PICTURE,TAB_MARK
item = PICTURE,TAB_GLOW
item = BUTTON,I_CHARACTER_2
item = BUTTON,I_SHIP_2
item = BUTTON,I_QUESTBOOK_2
item = BUTTON,I_ALCHEMY_2
item = BUTTON,I_ITEMS_2
item = BUTTON,I_NATIONS_2
item = STRINGCOLLECTION,STR_BUTTONS
item = STRINGCOLLECTION,STR_TITLE
item = 400,IMAGECOLLECTION,KEY_BTNS
item = 400,STRINGCOLLECTION,KEY_STRS
item = IMAGECOLLECTION,ADD_INFO
item = FORMATEDTEXT,WEIGHT
item = FORMATEDTEXT,MONEY
item = FORMATEDTEXT,CURRENT_DATE_CAPTION
item = ALERT,A_QUESTBOOK
item = ALERT,A_RECIPE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 20,FRAME,NATIONS_FRAME
item = 20,TABLE,TABLE_NATIONS
item = 20,FRAME,NATION_RELATION_FRAME
item = 30,FORMATEDTEXT,NATION_RELATION_CAPTION
item = 20,FRAME,SHIP_FLAG_FRAME
item = 30,FORMATEDTEXT,SHIP_FLAG_CAPTION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 20,IMAGECOLLECTION,NATION_RELATION_PICTURES
item = 20,FORMATEDTEXT,NATION_RELATION_ENGLAND
item = 20,FORMATEDTEXT,NATION_RELATION_FRANCE
item = 20,FORMATEDTEXT,NATION_RELATION_SPAIN
item = 20,FORMATEDTEXT,NATION_RELATION_HOLLAND
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 20,PICTURE,FlagPic
item = 20,TEXTBUTTON2,FLAGS
item = 20,BUTTON,LEFTCHANGE_NATION
item = 20,BUTTON,RIGHTCHANGE_NATION
item = FORMATEDTEXT,INFO_CLICK
item = FORMATEDTEXT,INFO_CLICK2


[MAIN_WINDOW]
show = 1
nodelist = SCROLL_LIST,EDIT_BOX,DOWN_BUTTON,UP_BUTTON,SHIP_BIG_PICTURE,MAIN_CHARACTER_PICTURE
nodelist = TABLE_LIST,TABLE_OTHER,SHIPS_SCROLL,CREW_MORALE_BUTTON,CREW_PARTITION

[MAIN_BACK]
bAbsoluteRectangle = 0
;position = -134,0,933,600
position = -169,-269,969,869
textureName = interfaces\Recon\bgr_interface.tga

[EB]
command = click,event:exitCancel

; анимация (крутится)
[DUST]
position 	= -200,-300,1000,1000
techniqueName	= iRotate
textureName	= interfaces\Recon\dust.tga
textureRect	= 0,0,1.0,1.0
color		= 200,200,200,200
rotate		= -0.03,0.005
speed		= 6000,0.0,0

; видео на заднем фоне
[V_NATION]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[A_QUESTBOOK]
position = 360,1,374,15

[A_RECIPE]
position = 457,1,471,15

[TOP_LINE]
position = -133,44,933,45
groupName = le_icons
picName = border_hs

[TAB_MARK]
position = 346,43,416,46
groupName = tabs2
picName = TabSelectedMark

[TAB_GLOW]
position = 326,0,437,44
groupName = tabs2
picName = TabSelected
blind = 1
blindUpTime = 2.0
blindDownTime = 2.0
blindMinColor = 50,128,128,128
blindMaxColor = 225,128,128,128

[STR_BUTTONS]
string = buttonCharacter,font:interface_normal,pos:{195,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonShip,font:interface_normal,pos:{282,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonAlchemy,font:interface_normal,pos:{458,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = buttonQuestBook,font:interface_normal,pos:{365,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}
string = Sel Items,font:interface_normal,pos:{542,16},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{C}

[STR_TITLE]
string = buttonNation,font:interface_normal,pos:{624,16},fc:{255,255,255,255},bc:{0,128,128,128},scale:1.11,state:{CS}

[KEY_BTNS]
groupName = keyboard_icons
picture = q,col:{255,75,75,75},pos:{91,11,119,38}
picture = e,col:{255,75,75,75},pos:{680,11,708,38}
picture = rmb,col:{255,128,128,128},pos:{537,561,565,588}
picture = esc,col:{255,128,128,128},pos:{680,561,708,588}

[KEY_STRS]
string = help,font:interface_normal,pos:{577,566},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{L}
string = back,font:interface_normal,pos:{724,566},fc:{125,255,255,255},bc:{0,128,128,128},scale:1.11,state:{L}

[ADD_INFO]
groupName = icons_char
picture = weight,col:{255,128,128,128},pos:{-117,16,-97,36}
picture = money,col:{255,128,128,128},pos:{-31,16,-11,36}

[WEIGHT]
command = click
command = rclick,select:WEIGHT,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = -89,19,-29,36
fontScale = 0.78
lineSpace = 10
alignment = left
bShowGlowCursor = 0

[MONEY]
command = click
command = rclick,select:MONEY,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = -9,19,77,36
fontScale = 0.78
lineSpace = 10
alignment = left
bShowGlowCursor = 0

[CURRENT_DATE_CAPTION]
command = click
position = 707,16,932,38
fontScale = 1.11
lineSpace = 10
alignment = center
string = Current Date and time

[I_CHARACTER_2]
bBreakCommand = 1
command = click
position = 136,0,253,44

[I_SHIP_2]
bBreakCommand = 1
command = click
position = 253,0,341,44

[I_QUESTBOOK_2]
bBreakCommand = 1
command = click
position = 341,0,427,44

[I_ALCHEMY_2]
bBreakCommand = 1
command = click
position = 427,0,499,44

[I_ITEMS_2]
bBreakCommand = 1
command = click
position = 499,0,585,44

[I_NATIONS_2]
bBreakCommand = 1
command = click
position = 585,0,663,44

[FADER]
bAbsoluteRectangle = 0
position = 0,0,800,600
leftColor = 150,50,50,0
topColor = 250,50,50,0
rightColor = 150,50,50,0
bottomColor = 150,50,50,0
borderColor = 0,0,0,0

[NATIONS_FRAME]
position = 10,65,605,550
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(205,150,150,150)

[TABLE_NATIONS]
command = click
command = deactivate,event:exitCancel
command = rclick,select:INFO_CLICK,event:ShowInfoWindow
position = 90,80,340,540
backimage = piclist=PAPIRUS, piccutuv=(0.0,0.0), color=(0,128,128,128)
selectimage = color=(0,200,120,55)
rowquantity = 6
colquantity = 6
vlinewidth = 1
hlineheight = 1
headerlineheight = 1
borderwidth = 0
bordercornersize = 0,0
fontcellvalignment = center
colswidth = 75,75,75,75,75,75
rowsheight = 75,75,75,75,75,75
NormalLineHeight = 75

[NATION_RELATION_FRAME]
captionheight = 25
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = 610,65,790,365
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(205,150,150,150)

[NATION_RELATION_CAPTION]
command = click
position = 610,68,790,88
font = interface_button
fontScale = 1.0
lineSpace = 10

[SHIP_FLAG_FRAME]
captionheight = 25
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = 610,370,790,550
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(200,150,150,150)

[SHIP_FLAG_CAPTION]
command = click
position = 610,373,790,393
font = interface_button
fontScale = 1.0
lineSpace = 10

[NATION_RELATION_PICTURES]
groupName = NATIONS
picture = ENGLAND,col:{255,128,128,128},pos:{620,98,652,130}
picture = FRANCE,col:{255,128,128,128},pos:{620,154,652,186}
picture = SPAIN,col:{255,128,128,128},pos:{620,210,652,242}
picture = HOLLAND,col:{255,128,128,128},pos:{620,266,652,298}

[NATION_RELATION_ENGLAND]
position = 660,96,780,128
lineSpace = 8
font = interface_normal
fontScale = 0.75
lineSpace = 13
valignment = 1

[NATION_RELATION_FRANCE]
position = 660,152,780,184
lineSpace = 8
font = interface_normal
fontScale = 0.75
lineSpace = 13
valignment = 1

[NATION_RELATION_SPAIN]
position = 660,208,780,242
lineSpace = 8
font = interface_normal
fontScale = 0.75
lineSpace = 13
valignment = 1

[NATION_RELATION_HOLLAND]
position = 660,264,780,296
lineSpace = 8
font = interface_normal
fontScale = 0.75
lineSpace = 13
valignment = 1

[FlagPic]
command = click
command = deactivate,event:exitCancel
command = rclick,select:FlagPic,event:ShowInfoWindow
position = 665,425,735,495
bShowGlowCursor = 0

[FLAGS]
bBreakCommand = 1
command = activate,event:FlagsPress,delay:150
command = click,event:FlagsPress,delay:150
command = rclick,select:FlagPic,event:ShowInfoWindow
command = deactivate,event:exitCancel
position = 620,514,780,540
strOffset = 3
font = interface_button
string = ChangeFlag
glowoffset = 0,0

[LEFTCHANGE_NATION]
bBreakCommand = 1
command = activate
command = click
command = rclick,select:FlagPic,event:ShowInfoWindow
position = 630,440,650,480
group = ICONS
picture = small left arrow
shadowOffset = 5,0

[RIGHTCHANGE_NATION]
bBreakCommand = 1
command = activate
command = click
command = rclick,select:FlagPic,event:ShowInfoWindow
position = 750,440,770,480
group = ICONS
picture = small right arrow
shadowOffset = -5,0

[INFO_CLICK]
command = click
command = deactivate,event:exitCancel
command = rclick,select:INFO_CLICK,event:ShowInfoWindow
bShowGlowCursor = 0
position = 599,76,768,366
lineSpace = 13

[INFO_CLICK2]
command = click
command = deactivate,event:exitCancel
command = rclick,select:FlagPic,event:ShowInfoWindow
bShowGlowCursor = 0
position = 30,76,566,551
lineSpace = 13
