;
; Recon Окно починки корабля
;

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 10,SLIDEPICTURE,DUST
;item = 20,VIDEORECTANGLE,V_SHIPYARD
item = 20,VIDEORECTANGLE

item = 555,FRAME,REPAIR_MAIN_FRAME
item = 555,pc,BUTTON,REPAIR_EXIT_BTN
item = 555,FORMATEDTEXT,REPAIR_WINDOW_TEXT
item = 556,TABLE,REPAIR_TABLE_LIST
;ship scroll
item = 555,SCROLLIMAGE,REPAIR_SHIPS_SCROLL
item = 555,BUTTON,REPAIR_LEFTSCROLLBUTTON
item = 555,BUTTON,REPAIR_RIGHTSCROLLBUTTON
item = 555,FORMATEDTEXT,REPAIR_SHIP_NAME
item = 555,PICTURE,REPAIR_MCHR_PICTURE
item = 556,PICTURE,REPAIR_MCHR_BORDER
item = 555,PICTURE,REPAIR_OTHER_PICTURE
item = 556,PICTURE,REPAIR_OTHER_BORDER
item = 555,FORMATEDTEXT,REPAIR_NAME_STR
item = 555,FORMATEDTEXT,REPAIR_LOCATION_STR

;hull
item = 557,PICTURE,REPAIR_HULL_PIC
item = 557,PICTURE,REPAIR_HULL_P_PIC
item = 600,FORMATEDTEXT,REPAIR_HULL_CAPTION
item = 600,FORMATEDTEXT,REPAIR_QTY_H
item = 600,BUTTON,REPAIR_RIGHT_H
item = 600,BUTTON,REPAIR_LEFT_H
item = 600,FORMATEDTEXT,REPAIR_HULL_R_STR
item = 600,FORMATEDTEXT,REPAIR_HULL_L_STR
;masts
item = 557,PICTURE,REPAIR_MAST_PIC
item = 557,PICTURE,REPAIR_MAST_P_PIC
item = 600,FORMATEDTEXT,REPAIR_MAST_CAPTION
item = 600,FORMATEDTEXT,REPAIR_QTY_M
item = 600,BUTTON,REPAIR_RIGHT_M
item = 600,BUTTON,REPAIR_LEFT_M
item = 600,FORMATEDTEXT,REPAIR_MAST_R_STR
item = 600,FORMATEDTEXT,REPAIR_MAST_L_STR
;sails
item = 557,PICTURE,REPAIR_SAIL_PIC
item = 557,PICTURE,REPAIR_SAIL_S_PIC
item = 600,FORMATEDTEXT,REPAIR_SAIL_CAPTION
item = 600,FORMATEDTEXT,REPAIR_QTY_S
item = 600,BUTTON,REPAIR_RIGHT_S
item = 600,BUTTON,REPAIR_LEFT_S
item = 600,FORMATEDTEXT,REPAIR_SAIL_R_STR
item = 600,FORMATEDTEXT,REPAIR_SAIL_L_STR

;bottom texts
item = 557,FORMATEDTEXT,REPAIR_SUPPLES_TEXT
item = 557,FORMATEDTEXT,REPAIR_NEEDS_TEXT
item = 557,FORMATEDTEXT,REPAIR_COST_T_TEXT
item = 557,FORMATEDTEXT,REPAIR_TIME_T_TEXT

;buttons
item = 555,TEXTBUTTON2,REPAIR_CALC_THIS
item = 555,TEXTBUTTON2,REPAIR_CALC_ALL
item = 555,TEXTBUTTON2,REPAIR_DISCARD_ALL
item = 555,TEXTBUTTON2,REPAIR_BEGIN
item = 555,TEXTBUTTON2,REPAIR_EXIT
item = WINDOW,REPAIR_WINDOW


;main window

[MAIN_BACK]
bAbsoluteRectangle = 0
position = -169,-269,969,869
textureName = interfaces\Recon\bgr_shipyard.tga

; анимация (крутится)
[DUST]
position 	= -200,-300,1000,1000
techniqueName	= iRotate
textureName	= interfaces\Recon\dust.tga
textureRect	= 0,0,1.0,1.0
color		= 200,200,200,200
rotate		= -0.03,0.005
speed		= 6000,0.0,0

;[V_SHIPYARD]
;bAbsoluteRectangle = 5
;position = -1,-1,1440,853
;color = 255,128,128,128

[REPAIR_MAIN_FRAME]
position = 65,60,736,540
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(190,128,128,128)
headerlineheight = 1
captionheight = 30
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captiondividerheight = 1

[REPAIR_EXIT_BTN]
position = 698,64,722,88
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
shadowColor = 0,0,0,0

[REPAIR_WINDOW_TEXT]
command = click
position = 130,66,670,86
font = interface_button
fontScale = 1.1
lineSpace = 10
alignment = center
Color = 255, 255, 255, 255
backoffset = 1, 2, 0, -2
string = titleSelfRepair

[REPAIR_TABLE_LIST]
position = 65,186,735,472
rowquantity = 3
colquantity = 5
selectimage = color=(0,200,120,55)
colswidth = 155,90,180,90,155
rowsheight = 90,90,90

;SHIP SCROLL

[REPAIR_SHIPS_SCROLL]
command = activate
command = deactivate,event:exitCancel
command = rightstep
command = leftstep
command = speedright
command = speedleft
command = click,select:REPAIR_SHIPS_SCROLL
position = 234,95,566,159
imageSize = 64,64
wDelta = 3
glowoffset = 0,0

[REPAIR_LEFTSCROLLBUTTON]
command = activate,select:REPAIR_SHIPS_SCROLL,com:speedleft:REPAIR_SHIPS_SCROLL
command = click,select:REPAIR_SHIPS_SCROLL,com:leftstep:REPAIR_SHIPS_SCROLL,com:activate:REPAIR_LEFTSCROLLBUTTON
position = 335,106,367,148
group = ICONS
picture = left arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[REPAIR_RIGHTSCROLLBUTTON]
command = activate,select:REPAIR_SHIPS_SCROLL,com:speedright:REPAIR_SHIPS_SCROLL
command = click,select:REPAIR_SHIPS_SCROLL,com:rightstep:REPAIR_SHIPS_SCROLL,com:activate:REPAIR_RIGHTSCROLLBUTTON
position = 432,106,464,148
group = ICONS
picture = right arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[REPAIR_SHIP_NAME]
position = 235,164,565,184
font = interface_button
fontScale = 1.0
lineSpace = 16
alignment = center
color = 255, 255, 255, 255

[REPAIR_MCHR_PICTURE]
position = 78,95,142,159
textureName = interfaces\portraits\128\face_1.tga

[REPAIR_MCHR_BORDER]
textureName = interfaces\emptyborder.tga
position = 78,95,142,159

[REPAIR_OTHER_PICTURE]
position = 661,95,722,159
textureName = interfaces\shipyardR.tga
bShowGlowCursor = 0

[REPAIR_OTHER_BORDER]
textureName = interfaces\emptyborder.tga
position = 661,95,722,159

[REPAIR_NAME_STR]
position = 140,95,234,159
fontScale = 0.9
lineSpace = 16
alignment = center
Color = 255,255,255,255

[REPAIR_LOCATION_STR]
position = 580,95,649,159
fontScale = 0.9
lineSpace = 16
alignment = center
Color = 255,255,255,255

;HULL

[REPAIR_HULL_PIC]
position = 227,200,304,274
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[REPAIR_HULL_P_PIC]
position = 500,193,574,267
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[REPAIR_HULL_CAPTION]
position = 300,193,505,213
font = interface_button
fontScale = 1.1
lineSpace = 10
alignment = center
Color = 255, 255, 255, 255
backoffset = 1, 2, 0, -2
string = HullRepair

[REPAIR_QTY_H]
position = 360,233,440,263
lineSpace = 26
font = Bold_numbers
fontScale = 1.2

[REPAIR_RIGHT_H]
command = click
command = rclick
group = ARROWS
picture = right
position = 460,225,480,265
disableColor = 255,128,128,128
shadowOffset = 3,2

[REPAIR_LEFT_H]
command = click
command = rclick
group = ARROWS
picture = left
position = 320,225,340,265
disableColor = 255,128,128,128
shadowOffset = 3,2

[REPAIR_HULL_R_STR]
position = 590,191,725,276
fontScale = 0.9
lineSpace = 16
alignment = center
Color = 255,255,255,255

[REPAIR_HULL_L_STR]
position = 77,191,212,276
fontScale = 0.9
lineSpace = 16
alignment = center
Color = 255,255,255,255

;MASTS

[REPAIR_MAST_PIC]
position = 228,280,308,360
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[REPAIR_MAST_P_PIC]
position = 500,283,574,357
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[REPAIR_MAST_CAPTION]
position = 300,283,505,373
font = interface_button
fontScale = 1.1
lineSpace = 10
alignment = center
Color = 255, 255, 255, 255
backoffset = 1, 2, 0, -2
string = MastRepair

[REPAIR_QTY_M]
position = 360,323,440,353
lineSpace = 26
font = Bold_numbers
fontScale = 1.2

[REPAIR_RIGHT_M]
command = click
command = rclick
group = ARROWS
picture = right
position = 460,315,480,355
disableColor = 255,128,128,128
shadowOffset = 3,2

[REPAIR_LEFT_M]
command = click
command = rclick
group = ARROWS
picture = left
position = 320,315,340,355
disableColor = 255,128,128,128
shadowOffset = 3,2

[REPAIR_MAST_R_STR]
position = 590,281,725,361
fontScale = 0.9
lineSpace = 16
alignment = center
Color = 255,255,255,255

[REPAIR_MAST_L_STR]
position = 77,281,212,361
fontScale = 0.9
lineSpace = 16
alignment = center
Color = 255,255,255,255

;SAILS

[REPAIR_SAIL_PIC]
position = 228,373,308,451
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[REPAIR_SAIL_S_PIC]
position = 500,373,574,447
textureName = interfaces\empty_spyglass-.tga
bShowGlowCursor = 0

[REPAIR_SAIL_CAPTION]
position = 300,373,505,463
font = interface_button
fontScale = 1.1
lineSpace = 10
alignment = center
Color = 255, 255, 255, 255
backoffset = 1, 2, 0, -2
string = SailRepair

[REPAIR_QTY_S]
position = 360,413,440,443
lineSpace = 26
font = Bold_numbers
fontScale = 1.2

[REPAIR_RIGHT_S]
command = click
command = rclick
group = ARROWS
picture = right
position = 460,405,480,445
disableColor = 255,128,128,128
shadowOffset = 3,2

[REPAIR_LEFT_S]
command = click
command = rclick
group = ARROWS
picture = left
position = 320,405,340,445
disableColor = 255,128,128,128
shadowOffset = 3,2

[REPAIR_SAIL_R_STR]
position = 590,371,725,451
fontScale = 0.9
lineSpace = 16
alignment = center
Color = 255,255,255,255

[REPAIR_SAIL_L_STR]
position = 72,371,217,451
fontScale = 0.9
lineSpace = 16
alignment = center
Color = 255,255,255,255

;BOTTOM TEXTS

[REPAIR_SUPPLES_TEXT]
position = 95,464,466,486
fontScale = 0.9
lineSpace = 16
alignment = left
color = 255,255,228,80

[REPAIR_NEEDS_TEXT]
position = 95,481,466,503
fontScale = 0.9
lineSpace = 16
alignment = left
color = 255,255,228,80

[REPAIR_COST_T_TEXT]
position = 440,464,735,486
fontScale = 0.9
lineSpace = 16
alignment = left
color = 255,255,228,80

[REPAIR_TIME_T_TEXT]
position = 440,481,735,503
fontScale = 0.9
lineSpace = 16
alignment = left
color = 255,255,228,80


;BUTTONS

[REPAIR_CALC_ALL]
command = deactivate,event:exitCancel
command = activate
command = click,select:REPAIR_SHIPS_SCROLL
position = 84,500,204,530
string = CalcAllShips
glowoffset = 0,0

[REPAIR_CALC_THIS]
command = deactivate,event:exitCancel
command = activate
command = click,select:REPAIR_SHIPS_SCROLL
position = 212,500,332,530
string = CalcThisShip
glowoffset = 0,0

[REPAIR_DISCARD_ALL]
command = deactivate,event:exitCancel
command = activate
command = click,select:REPAIR_SHIPS_SCROLL
position = 340,500,460,530
string = SC_DiscardAll
glowoffset = 0,0

[REPAIR_BEGIN]
bBreakCommand
command = deactivate,event:exitCancel
command = activate
command = click
position = 468,500,588,530
string = RepairShipShort
glowoffset = 0,0

[REPAIR_EXIT]
bBreakCommand
command = click,event:exitCancel
command = deactivate,event:exitCancel
command = activate
position = 596,500,716,530
string = Exit
glowoffset = 0,0
