;
; AlexBlade - Интерфейс изменения внешнего вида корабля
;

[MAIN]
; задний фон
item = 10,WINDOW,BACK_WINDOW
item = 10,MODELVIEWER,MODEL_VIEWER_TEST
item = 50,FORMATEDTEXT,SHIP_NAME_TEXT
item = 50,FORMATEDTEXT,SHIP_TYPE_TEXT
item = 300,pc,BUTTON,EXIT_BTN

;;;
item = 20,WINDOW,MAIN_WINDOW
item = 20,FRAME,SELECT_CHANGE_FRAME
item = 20,FRAME,CURRENT_CHANGE_FRAME
item = 200,TABLE,TABLE_CHANGES
item = 100,TITLE,TITLE
item = 300,BUTTON,CLOSE_CURRENT_CHANGE_BUTTON
;;;
item = 30,PICTURE,CHARACTER_PICTURE
item = 100,FORMATEDTEXT,CHARACTER_NAME
item = 40,PICTURE,CHARACTER_FRAME
item = 40,IMAGECOLLECTION,CHARACTER_MONEY_PIC
item = 40,FORMATEDTEXT,CHARACTER_MONEY_TEXT
;;;;
item = 100,TEXTBUTTON2,DISCARD_BTN
item = 100,TEXTBUTTON2,DISCARD_ALL_BTN
;;;;
item = 100,FORMATEDTEXT,SUMMARY_TEXT
item = 150,TABLE,TABLE_PRICES
item = 100,TEXTBUTTON2,BUTTON_BUY
;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 100,WINDOW,SAILS_GERALD_WINDOW
item = 100,FORMATEDTEXT,SAILS_GERALD_UNAVAILABLE
item = 100,TEXTBUTTON2,REMOVE_GERALD_BTN
item = 200,TABLE,TABLE_SAILS_GERALD
item = 200,SCROLLER,TABLE_SAILS_GERALD_SCROLL
;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 100,WINDOW,SAILS_COLOR_WINDOW
item = 200,TABLE,TABLE_SAILS_COLOR
item = 200,SCROLLER,TABLE_SAILS_COLOR_SCROLL
;;;;;;;;;;;;;;;;;;;;;;;;;
item = 100,WINDOW,SAILS_MATERIAL_WINDOW
item = 200,TABLE,TABLE_SAILS_MATERIAL
item = 20,FRAME,SAILS_MATERIAL_ATTENTION_FRAME
item = 100,FORMATEDTEXT,SAILS_MATERIAL_ATTENTION_TITLE
item = 100,FORMATEDTEXT,SAILS_MATERIAL_ATTENTION
;;;;;;;;;;;;;;;;;;;;;;;;;
item = 100,WINDOW,HULL_COLOR_WINDOW
item = 100,FORMATEDTEXT,HULL_COLOR_UNAVAILABLE
item = 200,TABLE,TABLE_HULL_COLOR
;;;;;;;;;;;;;;;;;;;;;;;;;
item = 100,WINDOW,DIALOG_WINDOW
item = 553,RECTANGLE,DIALOG_FADER
item = 554,SLIDEPICTURE,DIALOG_DUST
item = 555,FRAME,DIALOG_FRAME
item = 555,PICTURE,DIALOG_EXIT_BUTTON
item = 555,FORMATEDTEXT,DIALOG_TEXT
item = 555,TEXTBUTTON2,DIALOG_OK_BUTTON
item = 555,TEXTBUTTON2,DIALOG_CANCEL_BUTTON
;;;;;;; DEBUG MODE ;;;;;;;
item = 10,RECTANGLE,PHOTO_MODE_GRID_RECTANGLE
item = 10,RECTANGLE,PHOTO_MODE_GRID_RECTANGLE1
item = 100,WINDOW,PHOTO_MODE_WINDOW

item = 100,TEXTBUTTON2,PHOTO_MODE_BUTTON
item = 200,FRAME,EXT_SETTINGS_FRAME
item = 200,TABLE,EXT_SETTINGS_TABLE

item = 300,SLIDER,PHOTO_MODE_SHIP_SPEED_SLIDE
item = 300,SLIDER,PHOTO_MODE_SHIP_IMMERSION_SLIDE
item = 300,SLIDER,PHOTO_MODE_WIND_ANGLE_SLIDE
item = 300,SLIDER,PHOTO_MODE_SKY_ANGLE_SLIDE

item = 300,BUTTON,PHOTO_MODE_INC_V_COEF_BUTTON
item = 300,BUTTON,PHOTO_MODE_DEC_V_COEF_BUTTON
item = 299,VIDEO,PHOTO_MODE_V_COEF_BACK
item = 300,PCEDITBOX,PHOTO_MODE_V_COEF_EDIT

item = 300,BUTTON,PHOTO_MODE_INC_GRID_POS_BUTTON
item = 300,BUTTON,PHOTO_MODE_DEC_GRID_POS_BUTTON
item = 299,VIDEO,PHOTO_MODE_GRID_POS_BACK
item = 300,PCEDITBOX,PHOTO_MODE_GRID_POS_EDIT

;item = 300,TEXTBUTTON2,PHOTO_MODE_HIDE_INTERFACE_BUTTON
item = 50,STRINGCOLLECTION,CONTROLS_HELP_TEXT

[BACK_WINDOW]
nodelist = MODEL_VIEWER_TEST,EXIT_BTN,PHOTO_MODE_BUTTON

[MAIN_WINDOW]
nodelist = SELECT_CHANGE_FRAME,CURRENT_CHANGE_FRAME,CLOSE_CURRENT_CHANGE_BUTTON,TABLE_CHANGES,SUMMARY_TEXT,TABLE_PRICES,BUTTON_BUY,TITLE
nodelist = SHIP_NAME_TEXT,SHIP_TYPE_TEXT,CHARACTER_PICTURE,CHARACTER_NAME,CHARACTER_FRAME,CHARACTER_MONEY_PIC,CHARACTER_MONEY_TEXT,DISCARD_ALL_BTN


[TABLE_PRICES]
position = -2,117,73,245
backimage = ""
borderwidth = 0
vlinewidth = 0
hlineheight = 0
headerlineheight = 1
bordercornersize = 0,0
rowquantity = 5
colquantity = 1
fontcellvalignment = bottom
fontcellalignment = right
fontcellscale = 0.75
fontcellcolor = 255,255,228,80
cellspacesize = 12,3
colswidth = 75
rowsheight = 0,32,32,32,32
NormalLineHeight = 28

[SUMMARY_TEXT]
color = 255,255,228,80
position = -140,377,60,392
alignment = right
lineSpace = 10
fontScale = 0.75

[BUTTON_BUY]
command = activate
command = click
command = deactivate,event:exitCancel
position = -120,392,66,420
string = OK
fontScale = 0.9
glowoffset = 0,0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[TITLE]
position = -127,97,73,117
stringOffset = 2
stringWidth = 267
fontScale = 0.75

[SELECT_CHANGE_FRAME]
command = click
command = deactivate,event:exitCancel
bAbsoluteRectangle = 0
captionheight = 20
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = -127,97,73,425
backColor = 255,128,32,32
bShowGlowCursor=0

[TABLE_CHANGES]
command = click
command = deactivate,event:exitCancel
command = upstep
command = downstep
position = -127,117,72,245
backimage = ""
borderwidth = 1
vlinewidth = 0
hlineheight = 1
headerlineheight = 1
bordercornersize = 0,0
rowquantity = 5
colquantity = 1
fontcellvalignment = top
fontcellalignment = left
fontcellscale = 0.8
cellspacesize = 12,6
colswidth = 199
rowsheight = 0,32,32,32,32
NormalLineHeight = 28

[CURRENT_CHANGE_FRAME]
command = click
bAbsoluteRectangle = 0
lefttop_size		= 0,0
leftbottom_size		= 0,0
position = 72,97,315,425
backColor = 255,128,32,32

[DISCARD_BTN]
command = activate
command = click
command = deactivate,event:exitCancel
position = 243,100,303,116
string = SC_Discard
fontScale = 0.66
strOffset = 2
glowoffset = 0,0

[DISCARD_ALL_BTN]
command = activate
command = click
command = deactivate,event:exitCancel
position = -120,255,-44,271
string = SC_DiscardAll
fontScale = 0.66
strOffset = 2
glowoffset = 0,0

[CLOSE_CURRENT_CHANGE_BUTTON]
command = click
position = 75,100,91,116
group = ICONS
picture = left arrow
pressPictureOffset = 0,0
shadowOffset = 1,1

[MODEL_VIEWER_TEST]
command = click
command = rclick
command = upstep
command = downstep
command = speedup
command = speeddown
command = deactivate,event:exitCancel
bAbsoluteRectangle = 0
position = -133,0,933,599
color = 255,128,128,128
bWheelUse = 1
bUseWheel = 1
moveMouseDoSelect=1
bShowGlowCursor=0
; moveMouseDoUnSelect=1

; ================================

[CHARACTER_FRAME]
textureName=interfaces\empty_frame2.tga
position = -127,6,-63,70

[CHARACTER_PICTURE]
command = click
command = deactivate,event:exitCancel
position = -127,6,-63,70
textureName = interfaces\portraits\128\face_1.tga
bShowGlowCursor = 0

[CHARACTER_NAME]
bAbsoluteRectangle = 0
position = -57,6,244,26
lineSpace = 12
alignment=left
font = INTERFACE_TITLE
fontScale = 0.85

[CHARACTER_MONEY_FRAME]
bAbsoluteRectangle = 0
position = -127,144,3,166
backColor = 255,128,32,32
lefttop_size		= 0,0
righttop_size		= 0,0
leftbottom_size		= 0,0
rightbottom_size	= 0,0

[CHARACTER_MONEY_TEXT]
position = -27,33,93,57
fontScale = 0.8
lineSpace = 14
alignment = left
color = 255,255,228,80

[CHARACTER_MONEY_PIC]
groupName = ICONS_CHAR
picture = Money,col:{255,128,128,128},pos:{-57,29,-33,53}

[SHIP_NAME_TEXT]
bAbsoluteRectangle = 0
position = 200,548,600,568
lineSpace = 20
font = INTERFACE_TITLE
fontScale = 1.1

[SHIP_TYPE_TEXT]
bAbsoluteRectangle = 0
position = 200,574,600,594
lineSpace = 20
font = INTERFACE_TITLE
fontScale = 0.9


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[SAILS_GERALD_WINDOW]
nodelist = CURRENT_CHANGE_FRAME,TABLE_SAILS_GERALD,TABLE_SAILS_GERALD_SCROLL,REMOVE_GERALD_BTN,DISCARD_BTN

[TABLE_SAILS_GERALD]
command = click,select:TABLE_SAILS_GERALD
command = deactivate,event:exitCancel
command = upstep
command = downstep
command = speeddown
command = speedup
position = 73,119,315,405
backimage = ""
borderwidth = 0
vlinewidth = 0
hlineheight = 0
headerlineheight = 1
bordercornersize = 0,0
rowquantity = 5
colquantity = 4
fontcellvalignment = top
fontcellalignment = left
fontcellscale = 0.85
cellspacesize = 0,0
colswidth = 60,60,60,60
rowsheight = 0,72,72,72,72
NormalLineHeight = 28
selectimage = color=(0,128,128,128)
scroller = TABLE_SAILS_GERALD_SCROLL
iscolselect=1
moveMouseDoSelect=1
moveMouseDoUnSelect=1


[TABLE_SAILS_GERALD_SCROLL]
command = activate
command = deactivate
command = downstep
command = upstep
command = click
position = 315,97,329,425
ownedcontrol = TABLE_SAILS_GERALD
bUseWheel = 1

[REMOVE_GERALD_BTN]
command = activate
command = click
command = deactivate,event:exitCancel
position = 176,100,236,116
string = Remove
fontScale = 0.66
strOffset = 2
glowoffset = 0,0

[SAILS_GERALD_UNAVAILABLE]
bAbsoluteRectangle = 0
position = 75,122,312,162
lineSpace = 20
font = INTERFACE_TITLE
fontScale = 0.9

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[SAILS_COLOR_WINDOW]
nodelist = CURRENT_CHANGE_FRAME,TABLE_SAILS_COLOR,TABLE_SAILS_COLOR_SCROLL,DISCARD_BTN

[TABLE_SAILS_COLOR]
command = click,select:TABLE_SAILS_COLOR,event:evtSelectSailsColor
command = deactivate,event:exitCancel
command = upstep
command = downstep
command = speeddown
command = speedup
position = 73,119,315,408
backimage = ""
borderwidth = 0
vlinewidth = 0
hlineheight = 1
headerlineheight = 1
bordercornersize = 0,0
rowquantity = 7
colquantity = 2
fontcellvalignment = top
fontcellalignment = left
fontcellscale = 0.75
fontlist1 = INTERFACE_TITLE
cellspacesize = 4,1
colswidth = 175,66
rowsheight = 0,48,48,48,48,48,48
NormalLineHeight = 28
bShowGlowCursor = 1
scroller = TABLE_SAILS_COLOR_SCROLL
moveMouseDoSelect=1
moveMouseDoUnSelect=1

[TABLE_SAILS_COLOR_SCROLL]
command = activate
command = deactivate
command = downstep
command = upstep
command = click
position = 315,97,329,425
ownedcontrol = TABLE_SAILS_COLOR
bUseWheel = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[SAILS_MATERIAL_WINDOW]
nodelist = CURRENT_CHANGE_FRAME,TABLE_SAILS_MATERIAL,SAILS_MATERIAL_ATTENTION_FRAME,SAILS_MATERIAL_ATTENTION_TITLE,SAILS_MATERIAL_ATTENTION,DISCARD_BTN

[TABLE_SAILS_MATERIAL]
command = click,select:TABLE_SAILS_MATERIAL
command = deactivate,event:exitCancel
command = upstep
command = downstep
command = speeddown
command = speedup
position = 73,119,315,408
backimage = ""
borderwidth = 0
vlinewidth = 0
hlineheight = 1
headerlineheight = 1
bordercornersize = 0,0
rowquantity = 6
colquantity = 2
fontcellvalignment = top
fontcellalignment = left
fontcellscale = 0.75
fontlist1 = INTERFACE_TITLE
cellspacesize = 6,2
colswidth = 170,72
rowsheight = 0,58,58,58,58,58
NormalLineHeight = 28
bShowGlowCursor = 1
moveMouseDoSelect=1
moveMouseDoUnSelect=1


[SAILS_MATERIAL_ATTENTION_FRAME]
command = click
bAbsoluteRectangle = 0
captionheight = 20
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = 	73,431,315,503
backColor = 255,128,32,32

[SAILS_MATERIAL_ATTENTION_TITLE]
bAbsoluteRectangle = 5
position = 73,433,315,453
lineSpace = 10
font = INTERFACE_TITLE
fontScale = 0.75

[SAILS_MATERIAL_ATTENTION]
bAbsoluteRectangle = 0
position = 79,457,309,497
lineSpace = 12
fontScale = 0.75
color = 255,156,156,156

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[HULL_COLOR_WINDOW]
nodelist = CURRENT_CHANGE_FRAME,TABLE_HULL_COLOR,DISCARD_BTN

[TABLE_HULL_COLOR]
command = click,select:TABLE_HULL_COLOR
command = deactivate,event:exitCancel
command = upstep
command = downstep
command = speeddown
command = speedup
position = 73,119,315,408
backimage = ""
borderwidth = 0
vlinewidth = 0
hlineheight = 1
headerlineheight = 1
bordercornersize = 0,0
rowquantity = 7
colquantity = 2
fontcellvalignment = top
fontcellalignment = left
fontcellscale = 0.75
fontlist1 = INTERFACE_TITLE
cellspacesize = 6,2
colswidth = 175,67
rowsheight = 0,48,48,48,48,48,48
bShowGlowCursor = 1
moveMouseDoSelect=1
moveMouseDoUnSelect=1


[HULL_COLOR_UNAVAILABLE]
bAbsoluteRectangle = 0
position = 75,122,312,162
lineSpace = 20
font = INTERFACE_TITLE
fontScale = 0.9

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[EXIT_BTN]
position = 899,6,927,34
group = ICONS_SPEC
picture = exit button
command = click
command = deactivate,event:exitCancel
shadowColor = 0,0,0,0
bShowGlowCursor = 0
shadowoffset = -1,-1

;;;;;;;;;;;;;; DIALOG WINDOW ;;;;;;;;;;;;;
[DIALOG_WINDOW]
nodelist = DIALOG_FADER,DIALOG_DUST,DIALOG_FRAME,DIALOG_EXIT_BUTTON,DIALOG_TEXT,DIALOG_OK_BUTTON,DIALOG_CANCEL_BUTTON

[DIALOG_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[DIALOG_DUST]
position 	= -200,-300,1000,1000
techniqueName	= iRotate
textureName	= interfaces\Recon\dust.tga
textureRect	= 0,0,1.0,1.0
color		= 200,200,200,200
rotate		= -0.03,0.005
speed		= 6000,0.0,0

[DIALOG_FRAME]
position = 230,190,570,340
backimage = piclist=RECON_ICONS, picname=confirm window, color=(250, 120, 120, 120)

[DIALOG_EXIT_BUTTON]
position = 546,193,566,213
groupName = ICONS_SPEC
picName = exit button
command = click
command = deactivate,event:exitCancel

[DIALOG_TEXT]
position = 255,220,545,270
lineSpace = 20

[DIALOG_OK_BUTTON]
command = deactivate,event:exitCancel
command = click
command = activate
command = rightstep,select:DIALOG_CANCEL_BUTTON
position = 258,300,398,332
string = Yes
glowoffset = 0,0

[DIALOG_CANCEL_BUTTON]
command = deactivate,event:exitCancel
command = click
command = activate
command = leftstep,select:DIALOG_OK_BUTTON
position = 402,300,542,332
string = Cancel
glowoffset = 0,0
;;;;;;;;;;;;; DIALOG WINDOW END ;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;; DEBUG PHOTO MODE CONTROLS ;;;;;;;;;;;;;;;;;;;;;;;
[PHOTO_MODE_WINDOW]
nodelist = EXT_SETTINGS_FRAME,EXT_SETTINGS_TABLE,PHOTO_MODE_SHIP_SPEED_SLIDE,PHOTO_MODE_SHIP_IMMERSION_SLIDE,PHOTO_MODE_WIND_ANGLE_SLIDE,PHOTO_MODE_DEC_GRID_POS_BUTTON,PHOTO_MODE_INC_GRID_POS_BUTTON,PHOTO_MODE_GRID_POS_EDIT,PHOTO_MODE_GRID_POS_BACK
nodelist = PHOTO_MODE_SKY_ANGLE_SLIDE,PHOTO_MODE_GRID_RECTANGLE,PHOTO_MODE_GRID_RECTANGLE1,PHOTO_MODE_DEC_V_COEF_BUTTON,PHOTO_MODE_INC_V_COEF_BUTTON,PHOTO_MODE_V_COEF_EDIT,PHOTO_MODE_V_COEF_BACK,CONTROLS_HELP_TEXT

[EXT_SETTINGS_FRAME]
command = click
command = deactivate,event:exitCancel
bAbsoluteRectangle = 0
captionheight = 20
captionimage = piclist=RECON_ICONS, picname=frame caption red short, color=(255,128,128,128)
position = 727,97,927,425
backColor = 255,128,32,32
bShowGlowCursor=0

[EXT_SETTINGS_TABLE]
command = deactivate,event:exitCancel
position = 727,97,926,405
backimage = ""
borderwidth = 1
vlinewidth = 0
hlineheight = 1
headerlineheight = 1
bordercornersize = 0,0
rowquantity = 7
colquantity = 1
fonttitle = INTERFACE_TITLE
fonttitlecolor = 255,255,255,255
fonttitlescale = 0.75
fonttitlealignment	= center
fonttitlevalignment	= top
fontcellvalignment = top
fontcellalignment = left
fontcellscale = 0.8
cellspacesize = 6,3
colswidth = 199
rowsheight = 20,48,48,48,48,48,48
NormalLineHeight = 28

[PHOTO_MODE_SHIP_SPEED_SLIDE]
command = leftstep
command = speedleft
command = rightstep
command = speedright
command = deactivate,event:exitCancel
command = click
command = rclick,select:PHOTO_MODE_SHIP_SPEED_SLIDE
moveMouseDoSelect=1
moveMouseDoUnselect = 1
position = 733,136,921,151
pointerWidth = 18
pointerHeight = 18
glowoffset = 0,0

[PHOTO_MODE_SHIP_IMMERSION_SLIDE]
command = leftstep
command = speedleft
command = rightstep
command = speedright
command = deactivate,event:exitCancel
command = click
command = rclick,select:PHOTO_MODE_WIND_ANGLE_SLIDE
moveMouseDoSelect=1
moveMouseDoUnselect = 1
position = 733,184,921,199
pointerWidth = 18
pointerHeight = 18
glowoffset = 0,0

[PHOTO_MODE_WIND_ANGLE_SLIDE]
command = leftstep
command = speedleft
command = rightstep
command = speedright
command = deactivate,event:exitCancel
command = click
command = rclick,select:PHOTO_MODE_WIND_ANGLE_SLIDE
moveMouseDoSelect=1
moveMouseDoUnselect = 1
position = 733,232,921,247
pointerWidth = 18
pointerHeight = 18
glowoffset = 0,0

[PHOTO_MODE_SKY_ANGLE_SLIDE]
command = leftstep
command = speedleft
command = rightstep
command = speedright
command = deactivate,event:exitCancel
command = click
command = rclick,select:PHOTO_MODE_SKY_ANGLE_SLIDE
moveMouseDoSelect=1
moveMouseDoUnselect = 1
position = 733,280,921,295
pointerWidth = 18
pointerHeight = 18
glowoffset = 0,0

[PHOTO_MODE_BUTTON]
command = deactivate,event:exitCancel
command = click
command = activate
position = 813,539,927,565
string = SC_PhotoMode
glowoffset = 0,0

;[PHOTO_MODE_HIDE_INTERFACE_BUTTON]
;command = deactivate,event:exitCancel
;command = click
;command = activate
;position = 813,501,927,527
;fontScale = 0.8
;string = SC_HideInterface
;glowoffset = 0,0

[PHOTO_MODE_INC_V_COEF_BUTTON]
command = click
command = deactivate,event:exitCancel
position = 905,328,921,344
group = ICONS
picture = right arrow
pressPictureOffset = 0,0
shadowOffset = 1,1

[PHOTO_MODE_DEC_V_COEF_BUTTON]
command = click
command = deactivate,event:exitCancel
position = 821,328,837,344
group = ICONS
picture = left arrow
pressPictureOffset = 0,0
shadowOffset = 1,1

[PHOTO_MODE_V_COEF_BACK]
bAbsoluteRectangle = 0
position = 840,323,902,349
sTexture = bigbutton
color = 120,60,80,70

[PHOTO_MODE_V_COEF_EDIT]
command = click,select:PHOTO_MODE_V_COEF_EDIT
command = deactivate,event:exitCancel
command = activate,event:confirmChange_V_COEF_EDIT
position = 840,323,902,349
moveMouseDoSelect=1
moveMouseDoUnselect = 1
strFont = interface_button
argbFontColor = 255,255,255,255
stringLength = 5
stringWidth = 80
stringalign = center
stringoffset = 9,3
MiddleImage = color=(0,128,128,128), piclist=MAIN_ICONS, picname=middle side button
excludechars = qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM ёйцукенгшщзхъфывапролджэячсмитьбю	ЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ!@#№$%^&*()_-+=~`'"|\/?:;<>,{}[]

[PHOTO_MODE_INC_GRID_POS_BUTTON]
command = click
command = deactivate,event:exitCancel
position = 905,376,921,392
group = ICONS
picture = right arrow
pressPictureOffset = 0,0
shadowOffset = 1,1

[PHOTO_MODE_DEC_GRID_POS_BUTTON]
command = click
command = deactivate,event:exitCancel
position = 821,376,837,392
group = ICONS
picture = left arrow
pressPictureOffset = 0,0
shadowOffset = 1,1

[PHOTO_MODE_GRID_POS_BACK]
bAbsoluteRectangle = 0
position = 840,371,902,397
sTexture = bigbutton
color = 120,60,80,70

[PHOTO_MODE_GRID_POS_EDIT]
command = click,select:PHOTO_MODE_GRID_POS_EDIT
command = deactivate,event:exitCancel
command = activate,event:confirmChange_GRID_POS_EDIT
position = 840,371,902,397
moveMouseDoSelect=1
moveMouseDoUnselect = 1
strFont = interface_button
argbFontColor = 255,255,255,255
stringLength = 5
stringWidth = 80
stringalign = center
stringoffset = 9,3
MiddleImage = color=(0,128,128,128), piclist=MAIN_ICONS, picname=middle side button
excludechars = qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM ёйцукенгшщзхъфывапролджэячсмитьбю	ЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ!@#№$%^&*()_-+=~`'"|\/?:;<>,{}[]

[PHOTO_MODE_GRID_RECTANGLE]
position = 0,0,0,0
leftColor = 155,220,220,220
topColor = 155,220,220,220
rightColor = 155,220,220,220
bottomColor = 155,220,220,220

[PHOTO_MODE_GRID_RECTANGLE1]
position = 0,0,0,0
leftColor = 155,220,220,220
topColor = 155,220,220,220
rightColor = 155,220,220,220
bottomColor = 155,220,220,220

[CONTROLS_HELP_TEXT]
string = SC_HideInterface,font:interface_normal,pos:{676,545},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.8,state:{СS}
