; ReCon Интерфейс "Окно Магазина".

[MAIN]
item = 10,PICTURE,MAIN_BACK
item = 15,VIDEORECTANGLE,V_TG
item = 25,SLIDEPICTURE,DUST

item = 30,FRAME,MAIN_FRAME
item = 35,FORMATEDTEXT,MAIN_CAPTION
item = 35,BUTTON,EXIT_BTN
;
item = 50,PICTURE,MAIN_CHARACTER_PICTURE
item = 50,PICTURE,OTHER_PICTURE
item = 55,PICTURE,BORDER_PICTURE_1
item = 55,PICTURE,BORDER_PICTURE_2
item = 50,FORMATEDTEXT,CAPACITY
item = 50,FORMATEDTEXT,STORE_CAPACITY
item = 50,FORMATEDTEXT,OUR_GOLD
item = 50,FORMATEDTEXT,TRADER_GOLD
;
item = 50,SCROLLIMAGE,SHIPS_SCROLL
item = 55,BUTTON,LEFTSCROLLBUTTON
item = 55,BUTTON,RIGHTSCROLLBUTTON
;
item = 50,PICTURE,TABBTN_1
item = 55,FORMATEDTEXT,TABSTR_1
item = 50,PICTURE,TABBTN_2
item = 55,FORMATEDTEXT,TABSTR_2
item = 50,PICTURE,TABBTN_3
item = 55,FORMATEDTEXT,TABSTR_3
item = 50,PICTURE,TABBTN_4
item = 55,FORMATEDTEXT,TABSTR_4
item = 50,PICTURE,TABBTN_5
item = 55,FORMATEDTEXT,TABSTR_5
;
item = 50,TABLE,TABLE_LIST
item = 55,SCROLLER,SCROLL_LIST
;
item = 50,TEXTBUTTON2,GOODSTRANSFER_BTN
item = WINDOW,MAIN_WINDOW
;
;  BOX_MOVE
item = 200,RECTANGLE,QTY_FADER
item = 201,FRAME,QTY_FRAME
item = 202,FORMATEDTEXT,QTY_CAPTION
item = 202,FORMATEDTEXT,QTY_TypeOperation
item = 202,FORMATEDTEXT,QTY_Result
item = 202,FORMATEDTEXT,QTY_INFO_SHIP_QTY
item = 202,FORMATEDTEXT,QTY_INFO_STORE_QTY
item = 202,FORMATEDTEXT,QTY_INFO_SHIP_PRICE
item = 202,FORMATEDTEXT,QTY_INFO_STORE_PRICE
item = 202,FORMATEDTEXT,QTY_GOODS_INFO
item = 202,FORMATEDTEXT,QTY_FOOD_INFO
item = 202,FORMATEDTEXT,QTY_Win_fix
item = 205,VIDEO,V_QTY_EDIT
item = 206,PCEDITBOX,QTY_EDIT
item = 207,BUTTON,QTY_ADD_BUTTON
item = 207,BUTTON,QTY_REMOVE_BUTTON
item = 207,BUTTON,QTY_ADD_ALL_BUTTON
item = 207,BUTTON,QTY_REMOVE_ALL_BUTTON
item = 207,TEXTBUTTON2,QTY_OK_BUTTON
item = 207,TEXTBUTTON2,QTY_CANCEL_BUTTON
item = 202,PICTURE,QTY_GOODS_PICTURE
item = 202,FORMATEDTEXT,FOOD_SHIP
item = 200,WINDOW,QTY_WINDOW
start = TABLE_LIST

[MAIN_BACK]
bAbsoluteRectangle = 0
position = -134,0,933,600
textureName = interfaces\Recon\bgr_store.tga

[V_TG]
bAbsoluteRectangle = 5
position = -1,-1,1440,853
color = 255,128,128,128

[DUST]
position = -200,-300,1000,1000
techniqueName = iRotate
textureName = interfaces\Recon\dust.tga
textureRect = 0,0,1.0,1.0
color = 200,200,200,200
rotate = -0.03,0.005
speed = 6000,0.0,0

[MAIN_WINDOW]
show = 1
nodelist = MAIN_BACK,V_TG,DUST,MAIN_FRAME,MAIN_CAPTION,MAIN_CHARACTER_PICTURE,OTHER_PICTURE,BORDER_PICTURE_1,BORDER_PICTURE_2,CAPACITY,STORE_CAPACITY,OUR_GOLD,EXIT_BTN
nodelist = TRADER_GOLD,SHIPS_SCROLL,LEFTSCROLLBUTTON,RIGHTSCROLLBUTTON,TABBTN_1,TABSTR_1,TABBTN_2,TABSTR_2,TABBTN_3,TABSTR_3,TABBTN_4,TABSTR_4,TABBTN_5,TABSTR_5
nodelist = TABLE_LIST,SCROLL_LIST,GOODSTRANSFER_BTN

[MAIN_FRAME]
captionheight = 24
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
position = 100,10,700,590
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(190,128,128,128)

[MAIN_CAPTION]
position = 100,14,700,34
font = interface_button
fontScale = 1.0
lineSpace = 10
alignment = center
Color = 255,255,255,200
string = titleStore

[EXIT_BTN]
position = 675,13,695,33
group = ICONS_SPEC
picture = exit button
command = click,event:exitCancel
command = deactivate,event:exitCancel
shadowColor = 0,0,0,0
bShowGlowCursor = 0
shadowoffset = -1,-1

[MAIN_CHARACTER_PICTURE]
position = 110,44,165,99
textureName = interfaces\portraits\128\face_1.tga

[OTHER_PICTURE]
position = 635,44,690,99
textureName = interfaces\store.tga

[BORDER_PICTURE_1]
textureName = interfaces\emptyborder.tga
position = 110,44,165,99

[BORDER_PICTURE_2]
textureName = interfaces\emptyborder.tga
position = 635,44,690,99

[CAPACITY]
position = 165,44,255,99
fontScale = 0.85
lineSpace = 16
alignment = center
Color = 255,255,255,255

[STORE_CAPACITY]
position = 545,44,635,99
fontScale = 0.85
lineSpace = 16
alignment = center
Color = 255,255,255,255

[OUR_GOLD]
position = 120,565,700,580
fontScale = 0.9
lineSpace = 15
alignment = left
Color = 255,255,255,156

[TRADER_GOLD]
position = 400,565,680,580
fontScale = 0.9
lineSpace = 15
alignment = right
Color = 255,255,255,156

[SHIPS_SCROLL]
command = activate
command = deactivate,event:ExitCancel
command = upstep,select:TABLE_LIST
command = downstep,select:TABLE_LIST
command = rightstep
command = leftstep
command = speedright
command = speedleft
command = click,select:SHIPS_SCROLL
position = 255,44,545,99
imageSize = 55,55
wDelta = 3
glowoffset = 0,0

[LEFTSCROLLBUTTON]
command = activate,select:SHIPS_SCROLL,com:speedleft:SHIPS_SCROLL
command = click,select:SHIPS_SCROLL,com:leftstep:SHIPS_SCROLL,com:activate:LEFTSCROLLBUTTON
position = 340,49,375,94
group = ICONS
picture = left arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[RIGHTSCROLLBUTTON]
command = activate,select:SHIPS_SCROLL,com:speedright:SHIPS_SCROLL
command = click,select:SHIPS_SCROLL,com:rightstep:SHIPS_SCROLL,com:activate:RIGHTSCROLLBUTTON
position = 425,49,460,94
group = ICONS
picture = right arrow
pressPictureOffset = 1,1
shadowOffset = 1,1
pressShadowOffset = 0,0
pressDelay = 10

[TABBTN_1]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
position = 110,110,196,135
groupName = TABS
picName = TabDeSelected
bShowGlowCursor = 0

[TABSTR_1]
position = 110,110,196,135
fontscale = 0.8
lineSpace = 12
valignment = 1
string = GoodsAll

[TABBTN_2]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
position = 201,110,287,135
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_2]
position = 201,110,287,135
fontscale = 0.8
lineSpace = 12
valignment = 1
string = GoodsOnShip

[TABBTN_3]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
position = 292,110,378,135
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_3]
position = 292,110,378,135
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Exports

[TABBTN_4]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
position = 383,110,469,135
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_4]
position = 383,110,469,135
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Imports

[TABBTN_5]
command = deactivate,event:exitCancel
command = click,event:eTabControlPress
position = 474,110,560,135
groupName = TABS
picName = TabSelected
bShowGlowCursor = 0

[TABSTR_5]
position = 474,110,560,135
fontscale = 0.8
lineSpace = 12
valignment = 1
string = Contrabands

[GOODSTRANSFER_BTN]
command = click,event:Autotrade_All
command = activate,event:Autotrade_All
command = deactivate,event:exitCancel
command = upstep
position = 570,110,690,132
string = TransferTreasurer
glowoffset = 0,0
fontScale = 0.75

[TABLE_LIST]
command = deactivate,event:exitCancel
command = click,select:TABLE_LIST
command = rclick,event:ShowHelpHint,select:TABLE_LIST
command = dblclick,event:ShowItemInfo,select:TABLE_LIST
command = activate,event:ShowItemInfo
command = upstep
command = downstep
command = rightstep,com:click:QTY_REMOVE_BUTTON
command = leftstep,com:click:QTY_ADD_BUTTON
command = speedright,com:click:QTY_REMOVE_ALL_BUTTON
command = speedleft,com:click:QTY_ADD_ALL_BUTTON
position = 100,134,690,560
scroller = SCROLL_LIST
vlinewidth = 1
hlineheight = 1
borderwidth = 1
rowquantity = 13
colquantity = 8
fontcellvalignment = center
colswidth = 60,60,60,160,60,65,60,64
rowsheight = 38,32,32,32,32,32,32,32,32,32,32,32,32
NormalLineHeight = 32

[SCROLL_LIST]
command = click, select:TABLE_LIST
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 690,134,700,557
ownedcontrol = TABLE_LIST
;;;;;;;;;;;;;;;

[QTY_WINDOW]
show = 0
nodelist = QTY_FADER,QTY_FRAME,QTY_EDIT,QTY_OK_BUTTON,QTY_CANCEL_BUTTON,QTY_TypeOperation,QTY_GOODS_INFO,QTY_GOODS_PICTURE,QTY_FOOD_INFO
nodelist = QTY_CAPTION,QTY_ADD_BUTTON,QTY_REMOVE_BUTTON,QTY_ADD_ALL_BUTTON,QTY_REMOVE_ALL_BUTTON,FOOD_SHIP,QTY_FADER
nodelist = QTY_INFO_STORE_QTY,QTY_INFO_SHIP_QTY,QTY_INFO_SHIP_PRICE,QTY_INFO_STORE_PRICE,QTY_Result,QTY_Win_fix,V_QTY_EDIT

[QTY_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[QTY_FRAME]
position = 130,150,670,520
backimage = piclist=RECON_PAPIRUS, picname=papirus, color=(235,150,150,150)
rowquantity = 2
colquantity = 1
hlineheight = 2
headerlineheight = 1
cellspacesize = 2,1
fontcellscale = 0.8
colswidth = 348
rowsheight = 30,444
vlinewidth = 1
captionheight = 30
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captiondividerheight = 1

[QTY_CAPTION]
bAbsoluteRectangle = 5
position = 239,155,572,185
font = interface_button
fontScale = 1.1
lineSpace = 10
alignment = center
Color = 255,255,255,200
backoffset = 1,2,0,-2

[V_QTY_EDIT]
bAbsoluteRectangle = 0
position = 365,430,442,455
sTexture = bigbutton
color = 120,60,80,70

[QTY_EDIT]
command = click,select:QTY_EDIT
command = deactivate,event:exitCancel
command = activate,event:confirmChangeQTY_EDIT
position = 373,430,436,457
strFont = interface_button
argbFontColor = 255,255,255,255
stringLength = 5
stringWidth = 80
stringalign = center
stringoffset = 9,3
MiddleImage = color=(0,128,128,128), piclist=MAIN_ICONS, picname=middle side button
excludechars = qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM ёйцукенгшщзхъфывапролджэячсмитьбю	ЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ!@#№$%^&*()_-+=~`'"|\/?:;<>,.{}[]

[QTY_ADD_ALL_BUTTON]
command = click,event:ADD_ALL_BUTTON
group = ARROWS
picture = left_all
position = 314,430,339,455
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_ADD_BUTTON]
command = click,event:ADD_BUTTON
group = ARROWS
picture = left
position = 342,430,367,455
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_REMOVE_BUTTON]
command = click,event:REMOVE_BUTTON
group = ARROWS
picture = right
position = 439,430,464,455
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_REMOVE_ALL_BUTTON]
command = click,event:REMOVE_ALL_BUTTON
command = activate
group = ARROWS
picture = right_all
position = 467,430,492,455
disableColor = 255,128,128,128
shadowOffset = 3,2

[QTY_OK_BUTTON]
command = activate
command = click,event:TransactionOK
command = deactivate,event:MouseRClickUP
position = 255,470,395,502
string = Ok
fontScale = 1
glowoffset = 0,0
command = rightstep,com:click:QTY_REMOVE_BUTTON
command = leftstep,com:click:QTY_ADD_BUTTON
command = speedright,com:click:QTY_REMOVE_ALL_BUTTON
command = speedleft,com:click:QTY_ADD_ALL_BUTTON

[QTY_CANCEL_BUTTON]
command = activate
command = click,event:exitCancel
command = deactivate,event:exitCancel
position = 410,470,550,502
string = Cancel
fontScale = 1
glowoffset = 0,0
command = rightstep,com:click:QTY_REMOVE_BUTTON
command = leftstep,com:click:QTY_ADD_BUTTON
command = speedright,com:click:QTY_REMOVE_ALL_BUTTON
command = speedleft,com:click:QTY_ADD_ALL_BUTTON

[QTY_TypeOperation]
position = 239,388,572,412
fontScale = 1.2
lineSpace = 20
alignment = center
backoffset = 1,2,0,-2
Color = 255,255,255,156

[QTY_RESULT]
position = 310,400,490,430
fontScale = 0.9
lineSpace = 15
alignment = center
Color = 255,255,255,156

[QTY_INFO_SHIP_QTY]
position = 209,433,315,458
fontScale = 1.2
lineSpace = 10
alignment = center
backoffset = 1,2,0,-2

[QTY_INFO_STORE_QTY]
position = 492,433,598,458
fontScale = 1.2
lineSpace = 10
alignment = center
backoffset = 1,2,0,-2

[QTY_INFO_SHIP_PRICE]
position = 209,391,315,431
fontScale = 0.9
lineSpace = 20
alignment = center
backoffset = 1,2,0,-2
Color = 255,255,255,156

[QTY_INFO_STORE_PRICE]
position = 492,391,598,431
fontScale = 0.9
lineSpace = 20
alignment = center
backoffset = 1,2,0,-2
Color = 255,255,255,156

[QTY_GOODS_INFO]
position = 211,190,661,374
fontScale = 1.0
lineSpace = 17
alignment = center
backoffset = 1,2,0,-2

[QTY_Win_fix]
command = click,event:None
command = activate,event:None
position = 150,150,650,520

[QTY_GOODS_PICTURE]
position = 135,235,215,315
textureName = interfaces\store.tga
bShowGlowCursor = 0

[QTY_FOOD_INFO]
position = 259,371,550,387
fontScale = 0.85
lineSpace = 15
alignment = center

[FOOD_SHIP]
position = 273,365,548,382
fontScale = 0.85
lineSpace = 15
alignment = center

