;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Sith Интерфейс отдыха
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[MAIN]
item = 70,RECTANGLE,WAIT_FADER
item = 71,SLIDEPICTURE,DUST
item = 72,FRAME,MAIN_FRAME
item = 73,STRINGCOLLECTION,ADD_TEXT
item = 73,SLIDER,HOURS_SLIDE
item = 80,PC,BUTTON,EXIT_BTN
item = 80,TEXTBUTTON2,OK_BTN
item = 80,TEXTBUTTON2,CANCEL_BTN
item = 90,FORMATEDTEXT,INFO_TEXT
item = 90,FORMATEDTEXT,CURRENT_DATE_CAPTION
item = 90,FORMATEDTEXT,RESTTIME_TEXT
item = 90,FORMATEDTEXT,TIME_TEXT
item = 90,FORMATEDTEXT,DAYS_INFO
item = 90,CHECKBUTTON,TIME_CHECK

[WAIT_FADER]
bAbsoluteRectangle = 5
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 200,0,0,0
rightColor = 200,0,0,0
bottomColor = 200,0,0,0
borderColor = 0,0,0,0

[DUST]
position 	= -200,-300,1000,1000
techniqueName	= iRotate
textureName	= interfaces\Recon\dust.tga
textureRect	= 0,0,1.0,1.0
color		= 200,200,200,200
rotate		= -0.03,0.005
speed		= 6000,0.0,0

[MAIN_FRAME]
position = 215,153,585,413
captionheight = 26
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captionoffset = 0,0,0,0
captiondividerheight = 1
backimage = piclist=RECON_ICONS_BIG, picname=confirm window caption, color=(255,150,150,150)

[ADD_TEXT]
string = RestTime,font:interface_normal,pos:{400,185},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.9,state:{CS}
string = RestFrom,font:interface_normal,pos:{305,210},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.9,state:{RS}
string = RestTo,font:interface_normal,pos:{305,245},fc:{255,255,255,255},bc:{0,128,128,128},scale:0.9,state:{RS}

[CURRENT_DATE_CAPTION]
position = 300,210,400,280
fontScale = 0.9
lineSpace = 18
color = 255,255,255,192

[RESTTIME_TEXT]
position = 300,245,400,315
fontScale = 0.9
lineSpace = 18
color = 255,255,255,192

[TIME_CHECK]
command = click,event:RefreshVariables
command = deactivate, event:exitCancel
position = 405,210,725,350
alignment = left
fontScale = 0.9
iconsize = 14,14
sectioninterval = 7
lineheight = 11
section1 = 0,0,RestNight
section2 = 0,0,RestMorning
section3 = 0,0,RestTimerM
section4 = 1,0,RestTimer
section5 = 0,0,RestDays
normalFontColor = 255,200,200,200
selectFontColor = 255,255,255,255
bShowGlowCursor = 0
exclusiveChoose = 1
textClickable = 0
rect_textoffset = 20,0,0,0

[EXIT_BTN]
position = 550,155,573,178
command = click,event:exitcancel
group = ICONS_SPEC
picture = exit button
shadowColor = 0,0,0,0

[TIME_TEXT]
position = 200,310,590,350
fontScale = 1.0
lineSpace = 20
alignment = center

[HOURS_SLIDE]
command = click
command = leftstep
command = speedleft
command = rightstep
command = speedright
command = deactivate,event:exitcancel
command = downstep
position = 250,331,550,351
pointerWidth = 18
pointerHeight = 18
glowoffset = 0,0

[OK_BTN]
command = click
command = activate
command = deactivate,event:exitcancel
command = rightstep
command = upstep
position = 253,373,398,406
string = Ok
glowoffset = 0,0

[CANCEL_BTN]
command = click,event:exitcancel
command = activate,event:exitcancel
command = deactivate,event:exitcancel
command = leftstep
command = upstep
position = 402,373,547,406
string = Cancel
glowoffset = 0,0

[INFO_TEXT]
position = 210,155,590,170
fontScale = 1.2
lineSpace = 1
font = interface_button
alignment = center
string = Rest

[DAYS_INFO]
position = 470,297,590,317
fontScale = 0.9
lineSpace = 18
color = 255,128,128,128
alignment = left
string = RestDaysNote
