;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Sith Интерфейс "Окно обучения"
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[MAIN]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	MAIN_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = RECTANGLE,FADER
item = FRAME,MAIN_FRAME
item = TOOLTIP_TITLERECT,TITLERECT
item = FORMATEDTEXT,TITLE
item = PICTURE,INFO_PICTURE
item = 100,VIDEORECTANGLE,INFO_VIDEO
item = 120,PICTURE,VFRAME
item = 120,FRAME,VFRAME_BORDER
item = 120,FORMATEDTEXT,ZOOM
item = 120,PICTURE,ZOOMPLUS
item = FORMATEDTEXT,INFO_TEXT
item = SCROLLER,SCROLL_TEXT
item = FORMATEDTEXT,CONTROLS_TEXT
item = FORMATEDTEXT,CONTROLS_IMG
item = TEXTBUTTON,B_OK
item = TEXTBUTTON,B_OK2
item = CHECKBUTTON,TUTORIAL_CHECKBOX
item = WINDOW,MAIN_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; INFO_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 600,VIDEORECTANGLE,INFO_VIDEOZ
item = 600,FRAME,FRAME_ZOOM
item = 600,PICTURE,VFRAMEZ
item = WINDOW,INFO_WINDOW
start = INFO_TEXT

[MAIN_WINDOW]
show = 1
nodelist = FADER,MAIN_FRAME,TITLE,TITLERECT,INFO_PICTURE
nodelist = INFO_VIDEO,VFRAME,VFRAME_BORDER,ZOOM,ZOOMPLUS,INFO_TEXT,SCROLL_TEXT,B_OK,B_OK2
nodelist = CONTROLS_TEXT,CONTROLS_IMG
nodelist = TUTORIAL_CHECKBOX


[FADER]
bAbsoluteRectangle = 15
position = -1,-1,800,600
leftColor = 200,0,0,0
topColor = 150,0,0,0
rightColor = 50,0,0,0
bottomColor = 255,0,0,0
borderColor = 0,0,0,0

[MAIN_FRAME]
position = 201,89,600,512
;position = 201,195,600,407
captionheight = 26
captionimage = piclist=RECON_ICONS, picname=frame caption red, color=(255,128,128,128)
captiondividerheight = 1

[TITLERECT]
position = 206,95,595,117

[TITLE]
position = 206,92,595,115
;position = 206,198,595,221
fontScale = 1.0
lineSpace = 6
alignment = center
font = INTERFACE_TITLE

[INFO_PICTURE]
position = 212,123,589,334
textureName = loading\salary.tga

[INFO_VIDEO]
position = 212,123,589,334
textureRect = 0,0,1.0,1.0
videoFile = Pirate.webm
color = 255,128,128,128
loop = 1
silent = 1

[VFRAME]
command = click
command = deactivate,event:exitCancel
command = rclick,select:VFRAME,event:ShowInfoWindow
position = 212,123,589,334
textureName = interfaces\empty_back.tga
bShowGlowCursor=0

[VFRAME_BORDER]
backimage = piclist=PAPER_FRAME, picname=paper, color=(245,50,50,50)
position = 212,123,589,334

[ZOOM]
font = KEYBOARD_SYMBOL
position = 195,310,249,429
fontScale = 0.65

[ZOOMPLUS]
groupName = icons
picName = pluss
position = 227,307,236,316

[INFO_TEXT]
position = 217,345,584,459
;position = 217,240,584,354
fontScale = 0.85
lineSpace = 16
scrollerName = SCROLL_TEXT
command = downstep
command = upstep
command = speeddown
command = speedup
command = deactivate,event:exitCancel
command = activate,select:INFO_TEXT
command = click,select:INFO_TEXT
moveMouseDoSelect=1
bShowGlowCursor=0

[CONTROLS_TEXT]
position = 212,473,301,489
;position = 212,368,301,384
alignment = right
fontScale = 0.85
lineSpace = 16
color = 255,255,128,0
font = interface_normal
string = Controls

[CONTROLS_IMG]
position = 306,470,439,492
;position = 306,365,439,387
alignment = left
fontScale = 0.65
lineSpace = 12
font = KEYBOARD_SYMBOL

[SCROLL_TEXT]
command = click,select:INFO_TEXT
command = deactivate,event:exitCancel
command = downstep
command = upstep
position = 584,345,595,459
;position = 584,240,595,354
ownedcontrol = INFO_TEXT
rollerHeight = 11

[B_OK]
command = activate
command = deactivate,event:exitCancel
command = click
command = rightstep
position = 345,467,456,495
;position = 345,362,456,390
string = OK
glowoffset = 0,0

[B_OK2]
command = activate
command = deactivate,event:exitCancel
command = click
command = rightstep
position = 456,467,567,495
;position = 456,362,567,390
string = OK
glowoffset = 0,0

[TUTORIAL_CHECKBOX]
command = activate
command = deactivate,event:exitCancel
command = click
position = 700,562,927,579
alignment = left
iconoffset = 9,-2
iconsize = 20,20
individualpos = 0
section1 = 0,0,Show tutorial
fontScale = 1.0
normalFontColor = 255,255,255,255
selectFontColor = 255,255,255,255
normalpiccolor = 255,155,155,155
textClickable = 0
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; INFO_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[INFO_WINDOW]
show = 0
nodelist = FRAME_ZOOM,INFO_VIDEOZ,VFRAMEZ

[INFO_VIDEOZ]
position = 23,89,778,512
textureRect = 0,0,1.0,1.0
videoFile = Pirate.webm
color = 255,128,128,128
loop = 1
silent = 1

[FRAME_ZOOM]
position = 23,89,778,512
backimage = piclist=PAPER_FRAME, picname=paper, color=(245,50,50,50)
topline_height		= 2
bottomline_height	= 2
leftline_width		= 2
rightline_width		= 2

[VFRAMEZ]
position = 23,89,778,512
textureName = interfaces\empty_back.tga

