; ========================== Interfaces sound ==========================
[Boarding_0]
name = INTERFACE\Russian\_GTBoard0.wav

[Boarding_1]
name = INTERFACE\Russian\_GTBoard2.wav

[Landing_0]
name = INTERFACE\Russian\_GTTown2.wav

[Abandon_0]
name = INTERFACE\Russian\_Abandon0.wav

[Abandon_1]
name = INTERFACE\Russian\_Abandon1.wav

[Abandon_2]
name = INTERFACE\Russian\_Abandon2.wav

[Abandon_3]
name = INTERFACE\Russian\_Abandon3.wav

[CrewDamage]
name = INTERFACE\Russian\_Damage1.wav

[ChargeBalls]
name = INTERFACE\Russian\_balls.wav

[ChargeGrapes]
name = INTERFACE\Russian\_grapes.wav

[ChargeKnippels]
name = INTERFACE\Russian\_chain.wav

[ChargeBombs]
name = INTERFACE\Russian\_bombs.wav

[Encounter_Map_0]
name = INTERFACE\Russian\_EvShip0.wav

[Encounter_Map_1]
name = INTERFACE\Russian\_EvShip1.wav

[Gotcha]
name = INTERFACE\Russian\_Gotcha.wav

[BortReload_cannonl]
minDistance = 20.0
maxDistance = 350.0
name = INTERFACE\Russian\_GunReadyL.wav

[BortReload_cannonr]
minDistance = 20.0
maxDistance = 350.0
name = INTERFACE\Russian\_GunReadyR.wav

[EvEnemy_0]
name = INTERFACE\Russian\_EvEnemy0.wav

[EvEnemy_1]
name = INTERFACE\Russian\_EvEnemy1.wav

[Yes_Cap_0]
name = INTERFACE\Russian\_Yes_Cap_0.wav

[toArm]
minDistance = 0.5
maxDistance = 20.0
volume = 1.0
name = VOICE\Russian\EvilPirates01.wav

[priest_bead]
minDistance = 0.0
maxDistance = 0.0
volume = 0.0
name = Voice\Russian\priest_bead.wav

; =============== КРИКИ ===============
; Крики мужиков
[warrior]
minDistance = 0.5
maxDistance = 15.0
volume = 3.5
name = Types\Russian\warrior05.wav
name = Types\Russian\warrior_dam02.wav
name = Types\Russian\warrior_dam03.wav
name = Types\Russian\warrior_dam01.wav
name = Types\Russian\warrior01.wav
name = Types\Russian\warrior02.wav
name = Types\Russian\warrior03.wav
name = Types\Russian\warrior04.wav
name = Types\Russian\warrior05.wav

; Крики скелетов
[skeleton]
minDistance = 0.5
maxDistance = 7.0
volume = 2.0
name = Types\Russian\skel.wav

[sold_weapon_off]
minDistance = 0.1
maxDistance = 50.0
volume = 2.0
name = Types\Russian\soldiers1.wav
name = Types\Russian\soldiers2.wav

;вопль обезьяны
[MonkeyScream]
minDistance = 0.65
maxDistance = 50.0
volume = 2.0
name = Types\Russian\monkey.wav
