; ========================== Interfaces sound ==========================
[Boarding_0]
name = INTERFACE\English\_GTBoard0.wav

[Boarding_1]
name = INTERFACE\English\_GTBoard2.wav

[Landing_0]
name = INTERFACE\English\_GTTown2.wav

[Abandon_0]
name = INTERFACE\English\_Abandon0.wav

[Abandon_1]
name = INTERFACE\English\_Abandon1.wav

[Abandon_2]
name = INTERFACE\English\_Abandon2.wav

[Abandon_3]
name = INTERFACE\English\_Abandon3.wav

[CrewDamage]
name = INTERFACE\English\_Damage1.wav

[ChargeBalls]
name = INTERFACE\English\_balls.wav

[ChargeGrapes]
name = INTERFACE\English\_grapes.wav

[ChargeKnippels]
name = INTERFACE\English\_chain.wav

[ChargeBombs]
name = INTERFACE\English\_bombs.wav

[Encounter_Map_0]
name = INTERFACE\English\_EvShip0.wav

[Encounter_Map_1]
name = INTERFACE\English\_EvShip1.wav

[Gotcha]
name = INTERFACE\English\_Gotcha.wav

[BortReload_cannonl]
minDistance = 20.0
maxDistance = 350.0
name = INTERFACE\English\_GunReadyL.wav

[BortReload_cannonr]	
minDistance = 20.0
maxDistance = 350.0
name = INTERFACE\English\_GunReadyR.wav

[EvEnemy_0]
name = INTERFACE\English\_EvEnemy0.wav

[EvEnemy_1]
name = INTERFACE\English\_EvEnemy1.wav

[Yes_Cap_0]
name = INTERFACE\English\_Yes_Cap_0.wav

[toArm]
minDistance = 0.5
maxDistance = 20.0
volume = 1.0
name = VOICE\English\EvilPirates01.wav

[priest_bead]
minDistance = 0.0
maxDistance = 0.0
volume = 0.0
name = Voice\English\priest_bead.wav

; =============== КРИКИ ===============
; Крики мужиков
[warrior]
minDistance = 0.5
maxDistance = 15.0
volume = 3.5
name = Types\English\warrior05.wav
name = Types\English\warrior_dam02.wav
name = Types\English\warrior_dam03.wav
name = Types\English\warrior_dam01.wav
name = Types\English\warrior01.wav
name = Types\English\warrior02.wav
name = Types\English\warrior03.wav
name = Types\English\warrior04.wav
name = Types\English\warrior05.wav

; Крики скелетов
[skeleton]
minDistance = 0.5
maxDistance = 7.0
volume = 2.0
name = Types\English\skel.wav

[sold_weapon_off]
minDistance = 0.1
maxDistance = 50.0
volume = 2.0
name = Types\English\soldiers1.wav
name = Types\English\soldiers2.wav

;вопль обезьяны
[MonkeyScream]
minDistance = 0.65
maxDistance = 50.0
volume = 2.0
name = Types\English\monkey.wav
